//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.02 at 04:13:19 PM MSK 
//


package ru.gov.zakupki.eruz.common._1;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.gov.zakupki.eruz.common._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.gov.zakupki.eruz.common._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PrintFormType }
     * 
     */
    public PrintFormType createPrintFormType() {
        return new PrintFormType();
    }

    /**
     * Create an instance of {@link AttachmentType }
     * 
     */
    public AttachmentType createAttachmentType() {
        return new AttachmentType();
    }

    /**
     * Create an instance of {@link AttachmentType.CryptoSigns }
     * 
     */
    public AttachmentType.CryptoSigns createAttachmentTypeCryptoSigns() {
        return new AttachmentType.CryptoSigns();
    }

    /**
     * Create an instance of {@link ExtPrintFormType }
     * 
     */
    public ExtPrintFormType createExtPrintFormType() {
        return new ExtPrintFormType();
    }

    /**
     * Create an instance of {@link OKSMRef }
     * 
     */
    public OKSMRef createOKSMRef() {
        return new OKSMRef();
    }

    /**
     * Create an instance of {@link AttachmentListType }
     * 
     */
    public AttachmentListType createAttachmentListType() {
        return new AttachmentListType();
    }

    /**
     * Create an instance of {@link OKVEDRef }
     * 
     */
    public OKVEDRef createOKVEDRef() {
        return new OKVEDRef();
    }

    /**
     * Create an instance of {@link ContractorRef }
     * 
     */
    public ContractorRef createContractorRef() {
        return new ContractorRef();
    }

    /**
     * Create an instance of {@link TimeZoneRef }
     * 
     */
    public TimeZoneRef createTimeZoneRef() {
        return new TimeZoneRef();
    }

    /**
     * Create an instance of {@link SchemeVersion }
     * 
     */
    public SchemeVersion createSchemeVersion() {
        return new SchemeVersion();
    }

    /**
     * Create an instance of {@link OKOPFRef }
     * 
     */
    public OKOPFRef createOKOPFRef() {
        return new OKOPFRef();
    }

    /**
     * Create an instance of {@link PassportRFType }
     * 
     */
    public PassportRFType createPassportRFType() {
        return new PassportRFType();
    }

    /**
     * Create an instance of {@link InternationalPassportRFType }
     * 
     */
    public InternationalPassportRFType createInternationalPassportRFType() {
        return new InternationalPassportRFType();
    }

    /**
     * Create an instance of {@link ETPRef }
     * 
     */
    public ETPRef createETPRef() {
        return new ETPRef();
    }

    /**
     * Create an instance of {@link ViolationType }
     * 
     */
    public ViolationType createViolationType() {
        return new ViolationType();
    }

    /**
     * Create an instance of {@link ContractorUserRightRef }
     * 
     */
    public ContractorUserRightRef createContractorUserRightRef() {
        return new ContractorUserRightRef();
    }

    /**
     * Create an instance of {@link ContactsType }
     * 
     */
    public ContactsType createContactsType() {
        return new ContactsType();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link ContractorExcludeReasonRef }
     * 
     */
    public ContractorExcludeReasonRef createContractorExcludeReasonRef() {
        return new ContractorExcludeReasonRef();
    }

    /**
     * Create an instance of {@link PrintFormType.Signature }
     * 
     */
    public PrintFormType.Signature createPrintFormTypeSignature() {
        return new PrintFormType.Signature();
    }

    /**
     * Create an instance of {@link AttachmentType.CryptoSigns.Signature }
     * 
     */
    public AttachmentType.CryptoSigns.Signature createAttachmentTypeCryptoSignsSignature() {
        return new AttachmentType.CryptoSigns.Signature();
    }

    /**
     * Create an instance of {@link ExtPrintFormType.Signature }
     * 
     */
    public ExtPrintFormType.Signature createExtPrintFormTypeSignature() {
        return new ExtPrintFormType.Signature();
    }

}
