//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.02 at 03:51:32 PM MSK 
//


package ru.gov.zakupki.eruz.types._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import ru.gov.zakupki.eruz.common._1.ETPRef;
import ru.gov.zakupki.eruz.common._1.ExtPrintFormType;
import ru.gov.zakupki.eruz.common._1.PrintFormType;


/**
 * Тип: Информация и документы об участнике закупки
 * 
 * <p>Java class for contractorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="contractorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="versionNumber" type="{http://zakupki.gov.ru/eruz/base/1}versionNumberType" minOccurs="0"/>
 *         &lt;element name="commonInfo" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="registryNum" type="{http://zakupki.gov.ru/eruz/base/1}eruzRegistryNumType" minOccurs="0"/>
 *                   &lt;element name="registryDT" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *                   &lt;element name="startRegDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                   &lt;element name="endRegDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                   &lt;element name="href" type="{http://zakupki.gov.ru/eruz/base/1}hrefType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="contractorInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="legalEntityRFInfo" type="{http://zakupki.gov.ru/eruz/types/1}legalEntityRFType"/>
 *                   &lt;element name="filialLegalEntityRFInfo" type="{http://zakupki.gov.ru/eruz/types/1}filialLegalEntityRFType"/>
 *                   &lt;element name="individualPersonRFInfo" type="{http://zakupki.gov.ru/eruz/types/1}individualPersonRFType"/>
 *                   &lt;element name="legalEntityForeignStateInRAFPInfo" type="{http://zakupki.gov.ru/eruz/types/1}legalEntityForeignStateInRAFPType"/>
 *                   &lt;element name="legalEntityForeignStateNotInRAFPInfo" type="{http://zakupki.gov.ru/eruz/types/1}legalEntityForeignStateNotInRAFPType"/>
 *                   &lt;element name="individualPersonForeignStateInfo" type="{http://zakupki.gov.ru/eruz/types/1}individualPersonForeignStateType"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="informationType" type="{http://zakupki.gov.ru/eruz/types/1}informationType"/>
 *         &lt;element name="ETP" type="{http://zakupki.gov.ru/eruz/common/1}ETPRef" minOccurs="0"/>
 *         &lt;element name="printFormInfo" type="{http://zakupki.gov.ru/eruz/common/1}printFormType" minOccurs="0"/>
 *         &lt;element name="extPrintFormInfo" type="{http://zakupki.gov.ru/eruz/common/1}extPrintFormType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="schemeVersion" use="required" type="{http://zakupki.gov.ru/eruz/base/1}schemeVersionType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "contractorType", propOrder = {
    "id",
    "versionNumber",
    "commonInfo",
    "contractorInfo",
    "informationType",
    "etp",
    "printFormInfo",
    "extPrintFormInfo"
})
public class ContractorType {

    protected Long id;
    protected Integer versionNumber;
    protected ContractorType.CommonInfo commonInfo;
    @XmlElement(required = true)
    protected ContractorType.ContractorInfo contractorInfo;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected InformationType informationType;
    @XmlElement(name = "ETP")
    protected ETPRef etp;
    protected PrintFormType printFormInfo;
    protected ExtPrintFormType extPrintFormInfo;
    @XmlAttribute(name = "schemeVersion", required = true)
    protected String schemeVersion;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setId(Long value) {
        this.id = value;
    }

    /**
     * Gets the value of the versionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getVersionNumber() {
        return versionNumber;
    }

    /**
     * Sets the value of the versionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setVersionNumber(Integer value) {
        this.versionNumber = value;
    }

    /**
     * Gets the value of the commonInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ContractorType.CommonInfo }
     *     
     */
    public ContractorType.CommonInfo getCommonInfo() {
        return commonInfo;
    }

    /**
     * Sets the value of the commonInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContractorType.CommonInfo }
     *     
     */
    public void setCommonInfo(ContractorType.CommonInfo value) {
        this.commonInfo = value;
    }

    /**
     * Gets the value of the contractorInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ContractorType.ContractorInfo }
     *     
     */
    public ContractorType.ContractorInfo getContractorInfo() {
        return contractorInfo;
    }

    /**
     * Sets the value of the contractorInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContractorType.ContractorInfo }
     *     
     */
    public void setContractorInfo(ContractorType.ContractorInfo value) {
        this.contractorInfo = value;
    }

    /**
     * Gets the value of the informationType property.
     * 
     * @return
     *     possible object is
     *     {@link InformationType }
     *     
     */
    public InformationType getInformationType() {
        return informationType;
    }

    /**
     * Sets the value of the informationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link InformationType }
     *     
     */
    public void setInformationType(InformationType value) {
        this.informationType = value;
    }

    /**
     * Gets the value of the etp property.
     * 
     * @return
     *     possible object is
     *     {@link ETPRef }
     *     
     */
    public ETPRef getETP() {
        return etp;
    }

    /**
     * Sets the value of the etp property.
     * 
     * @param value
     *     allowed object is
     *     {@link ETPRef }
     *     
     */
    public void setETP(ETPRef value) {
        this.etp = value;
    }

    /**
     * Gets the value of the printFormInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PrintFormType }
     *     
     */
    public PrintFormType getPrintFormInfo() {
        return printFormInfo;
    }

    /**
     * Sets the value of the printFormInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrintFormType }
     *     
     */
    public void setPrintFormInfo(PrintFormType value) {
        this.printFormInfo = value;
    }

    /**
     * Gets the value of the extPrintFormInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ExtPrintFormType }
     *     
     */
    public ExtPrintFormType getExtPrintFormInfo() {
        return extPrintFormInfo;
    }

    /**
     * Sets the value of the extPrintFormInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtPrintFormType }
     *     
     */
    public void setExtPrintFormInfo(ExtPrintFormType value) {
        this.extPrintFormInfo = value;
    }

    /**
     * Gets the value of the schemeVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemeVersion() {
        return schemeVersion;
    }

    /**
     * Sets the value of the schemeVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemeVersion(String value) {
        this.schemeVersion = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="registryNum" type="{http://zakupki.gov.ru/eruz/base/1}eruzRegistryNumType" minOccurs="0"/>
     *         &lt;element name="registryDT" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
     *         &lt;element name="startRegDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *         &lt;element name="endRegDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *         &lt;element name="href" type="{http://zakupki.gov.ru/eruz/base/1}hrefType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "registryNum",
        "registryDT",
        "startRegDate",
        "endRegDate",
        "href"
    })
    public static class CommonInfo {

        protected String registryNum;
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar registryDT;
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar startRegDate;
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar endRegDate;
        protected String href;

        /**
         * Gets the value of the registryNum property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRegistryNum() {
            return registryNum;
        }

        /**
         * Sets the value of the registryNum property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRegistryNum(String value) {
            this.registryNum = value;
        }

        /**
         * Gets the value of the registryDT property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getRegistryDT() {
            return registryDT;
        }

        /**
         * Sets the value of the registryDT property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setRegistryDT(XMLGregorianCalendar value) {
            this.registryDT = value;
        }

        /**
         * Gets the value of the startRegDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getStartRegDate() {
            return startRegDate;
        }

        /**
         * Sets the value of the startRegDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setStartRegDate(XMLGregorianCalendar value) {
            this.startRegDate = value;
        }

        /**
         * Gets the value of the endRegDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getEndRegDate() {
            return endRegDate;
        }

        /**
         * Sets the value of the endRegDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setEndRegDate(XMLGregorianCalendar value) {
            this.endRegDate = value;
        }

        /**
         * Gets the value of the href property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHref() {
            return href;
        }

        /**
         * Sets the value of the href property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHref(String value) {
            this.href = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="legalEntityRFInfo" type="{http://zakupki.gov.ru/eruz/types/1}legalEntityRFType"/>
     *         &lt;element name="filialLegalEntityRFInfo" type="{http://zakupki.gov.ru/eruz/types/1}filialLegalEntityRFType"/>
     *         &lt;element name="individualPersonRFInfo" type="{http://zakupki.gov.ru/eruz/types/1}individualPersonRFType"/>
     *         &lt;element name="legalEntityForeignStateInRAFPInfo" type="{http://zakupki.gov.ru/eruz/types/1}legalEntityForeignStateInRAFPType"/>
     *         &lt;element name="legalEntityForeignStateNotInRAFPInfo" type="{http://zakupki.gov.ru/eruz/types/1}legalEntityForeignStateNotInRAFPType"/>
     *         &lt;element name="individualPersonForeignStateInfo" type="{http://zakupki.gov.ru/eruz/types/1}individualPersonForeignStateType"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "legalEntityRFInfo",
        "filialLegalEntityRFInfo",
        "individualPersonRFInfo",
        "legalEntityForeignStateInRAFPInfo",
        "legalEntityForeignStateNotInRAFPInfo",
        "individualPersonForeignStateInfo"
    })
    public static class ContractorInfo {

        protected LegalEntityRFType legalEntityRFInfo;
        protected FilialLegalEntityRFType filialLegalEntityRFInfo;
        protected IndividualPersonRFType individualPersonRFInfo;
        protected LegalEntityForeignStateInRAFPType legalEntityForeignStateInRAFPInfo;
        protected LegalEntityForeignStateNotInRAFPType legalEntityForeignStateNotInRAFPInfo;
        protected IndividualPersonForeignStateType individualPersonForeignStateInfo;

        /**
         * Gets the value of the legalEntityRFInfo property.
         * 
         * @return
         *     possible object is
         *     {@link LegalEntityRFType }
         *     
         */
        public LegalEntityRFType getLegalEntityRFInfo() {
            return legalEntityRFInfo;
        }

        /**
         * Sets the value of the legalEntityRFInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link LegalEntityRFType }
         *     
         */
        public void setLegalEntityRFInfo(LegalEntityRFType value) {
            this.legalEntityRFInfo = value;
        }

        /**
         * Gets the value of the filialLegalEntityRFInfo property.
         * 
         * @return
         *     possible object is
         *     {@link FilialLegalEntityRFType }
         *     
         */
        public FilialLegalEntityRFType getFilialLegalEntityRFInfo() {
            return filialLegalEntityRFInfo;
        }

        /**
         * Sets the value of the filialLegalEntityRFInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link FilialLegalEntityRFType }
         *     
         */
        public void setFilialLegalEntityRFInfo(FilialLegalEntityRFType value) {
            this.filialLegalEntityRFInfo = value;
        }

        /**
         * Gets the value of the individualPersonRFInfo property.
         * 
         * @return
         *     possible object is
         *     {@link IndividualPersonRFType }
         *     
         */
        public IndividualPersonRFType getIndividualPersonRFInfo() {
            return individualPersonRFInfo;
        }

        /**
         * Sets the value of the individualPersonRFInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link IndividualPersonRFType }
         *     
         */
        public void setIndividualPersonRFInfo(IndividualPersonRFType value) {
            this.individualPersonRFInfo = value;
        }

        /**
         * Gets the value of the legalEntityForeignStateInRAFPInfo property.
         * 
         * @return
         *     possible object is
         *     {@link LegalEntityForeignStateInRAFPType }
         *     
         */
        public LegalEntityForeignStateInRAFPType getLegalEntityForeignStateInRAFPInfo() {
            return legalEntityForeignStateInRAFPInfo;
        }

        /**
         * Sets the value of the legalEntityForeignStateInRAFPInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link LegalEntityForeignStateInRAFPType }
         *     
         */
        public void setLegalEntityForeignStateInRAFPInfo(LegalEntityForeignStateInRAFPType value) {
            this.legalEntityForeignStateInRAFPInfo = value;
        }

        /**
         * Gets the value of the legalEntityForeignStateNotInRAFPInfo property.
         * 
         * @return
         *     possible object is
         *     {@link LegalEntityForeignStateNotInRAFPType }
         *     
         */
        public LegalEntityForeignStateNotInRAFPType getLegalEntityForeignStateNotInRAFPInfo() {
            return legalEntityForeignStateNotInRAFPInfo;
        }

        /**
         * Sets the value of the legalEntityForeignStateNotInRAFPInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link LegalEntityForeignStateNotInRAFPType }
         *     
         */
        public void setLegalEntityForeignStateNotInRAFPInfo(LegalEntityForeignStateNotInRAFPType value) {
            this.legalEntityForeignStateNotInRAFPInfo = value;
        }

        /**
         * Gets the value of the individualPersonForeignStateInfo property.
         * 
         * @return
         *     possible object is
         *     {@link IndividualPersonForeignStateType }
         *     
         */
        public IndividualPersonForeignStateType getIndividualPersonForeignStateInfo() {
            return individualPersonForeignStateInfo;
        }

        /**
         * Sets the value of the individualPersonForeignStateInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link IndividualPersonForeignStateType }
         *     
         */
        public void setIndividualPersonForeignStateInfo(IndividualPersonForeignStateType value) {
            this.individualPersonForeignStateInfo = value;
        }

    }

}
