//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.02 at 04:13:19 PM MSK 
//


package ru.gov.zakupki.eruz.types._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import ru.gov.zakupki.eruz.common._1.AttachmentListType;
import ru.gov.zakupki.eruz.common._1.AttachmentType;
import ru.gov.zakupki.eruz.common._1.ContactsType;
import ru.gov.zakupki.eruz.common._1.InternationalPassportRFType;
import ru.gov.zakupki.eruz.common._1.OKOPFRef;
import ru.gov.zakupki.eruz.common._1.PassportRFType;
import ru.gov.zakupki.eruz.common._1.PersonType;
import ru.gov.zakupki.eruz.common._1.TimeZoneRef;


/**
 * Тип: Филиал юридического лица РФ
 * 
 * <p>Java class for filialLegalEntityRFType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="filialLegalEntityRFType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="legalEntityInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="legalEntityRFDataInfo">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{http://zakupki.gov.ru/eruz/types/1}legalEntityRFDataType">
 *                           &lt;sequence>
 *                             &lt;element name="OKOPF" type="{http://zakupki.gov.ru/eruz/common/1}OKOPFRef" minOccurs="0"/>
 *                             &lt;element name="majorTaxPayerKPP" type="{http://zakupki.gov.ru/eruz/base/1}kppType" minOccurs="0"/>
 *                             &lt;element name="EGRULStatementInfo" type="{http://zakupki.gov.ru/eruz/common/1}attachmentType" minOccurs="0"/>
 *                             &lt;element name="registryNum" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://zakupki.gov.ru/eruz/base/1>eruzRegistryNumType">
 *                                     &lt;attribute name="isArchived" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="managingOrganization" type="{http://zakupki.gov.ru/eruz/types/1}managingOrganizationType" minOccurs="0"/>
 *                   &lt;element name="informationPersons" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="informationPersonInfo" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="nameInfo" type="{http://zakupki.gov.ru/eruz/common/1}personType"/>
 *                                       &lt;element name="position" type="{http://zakupki.gov.ru/eruz/base/1}positionType"/>
 *                                       &lt;element name="identityDocInfo" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;choice>
 *                                                 &lt;element name="passportRFInfo" type="{http://zakupki.gov.ru/eruz/common/1}passportRFType"/>
 *                                                 &lt;element name="internationalPassportRFInfo" type="{http://zakupki.gov.ru/eruz/common/1}internationalPassportRFType"/>
 *                                                 &lt;element name="passportForeignInfo" type="{http://zakupki.gov.ru/eruz/types/1}passportForeignType"/>
 *                                                 &lt;element name="sojournPermitInfo" type="{http://zakupki.gov.ru/eruz/types/1}sojournPermitType"/>
 *                                                 &lt;element name="permamentResidencyInfo" type="{http://zakupki.gov.ru/eruz/types/1}permamentResidencyType"/>
 *                                               &lt;/choice>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="INN" type="{http://zakupki.gov.ru/eruz/base/1}innIndividualType" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="filialInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="filialLegalEntityRFDataInfo">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="KPP" type="{http://zakupki.gov.ru/eruz/base/1}kppType"/>
 *                             &lt;element name="fullName" type="{http://zakupki.gov.ru/eruz/base/1}text1000Type"/>
 *                             &lt;element name="factAdressInfo" type="{http://zakupki.gov.ru/eruz/types/1}factAdressType"/>
 *                             &lt;element name="maxPrice" type="{http://zakupki.gov.ru/eruz/base/1}moneyMaxLengthToPoint21Type"/>
 *                             &lt;element name="timeZoneInfo" type="{http://zakupki.gov.ru/eruz/common/1}timeZoneRef"/>
 *                             &lt;element name="isParticipant" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="isSubcontractor" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="filialContactInfo">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{http://zakupki.gov.ru/eruz/common/1}contactsType">
 *                           &lt;sequence>
 *                             &lt;element name="postAdress" type="{http://zakupki.gov.ru/eruz/base/1}text2000Type" minOccurs="0"/>
 *                             &lt;element name="url" type="{http://zakupki.gov.ru/eruz/base/1}hrefType" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="attachmentsInfo">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="consentDecisionsInfo" type="{http://zakupki.gov.ru/eruz/common/1}attachmentListType"/>
 *                             &lt;element name="foundingDocsCopyInfo" type="{http://zakupki.gov.ru/eruz/common/1}attachmentListType" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "filialLegalEntityRFType", propOrder = {
    "legalEntityInfo",
    "filialInfo"
})
public class FilialLegalEntityRFType {

    @XmlElement(required = true)
    protected FilialLegalEntityRFType.LegalEntityInfo legalEntityInfo;
    @XmlElement(required = true)
    protected FilialLegalEntityRFType.FilialInfo filialInfo;

    /**
     * Gets the value of the legalEntityInfo property.
     * 
     * @return
     *     possible object is
     *     {@link FilialLegalEntityRFType.LegalEntityInfo }
     *     
     */
    public FilialLegalEntityRFType.LegalEntityInfo getLegalEntityInfo() {
        return legalEntityInfo;
    }

    /**
     * Sets the value of the legalEntityInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilialLegalEntityRFType.LegalEntityInfo }
     *     
     */
    public void setLegalEntityInfo(FilialLegalEntityRFType.LegalEntityInfo value) {
        this.legalEntityInfo = value;
    }

    /**
     * Gets the value of the filialInfo property.
     * 
     * @return
     *     possible object is
     *     {@link FilialLegalEntityRFType.FilialInfo }
     *     
     */
    public FilialLegalEntityRFType.FilialInfo getFilialInfo() {
        return filialInfo;
    }

    /**
     * Sets the value of the filialInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilialLegalEntityRFType.FilialInfo }
     *     
     */
    public void setFilialInfo(FilialLegalEntityRFType.FilialInfo value) {
        this.filialInfo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="filialLegalEntityRFDataInfo">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="KPP" type="{http://zakupki.gov.ru/eruz/base/1}kppType"/>
     *                   &lt;element name="fullName" type="{http://zakupki.gov.ru/eruz/base/1}text1000Type"/>
     *                   &lt;element name="factAdressInfo" type="{http://zakupki.gov.ru/eruz/types/1}factAdressType"/>
     *                   &lt;element name="maxPrice" type="{http://zakupki.gov.ru/eruz/base/1}moneyMaxLengthToPoint21Type"/>
     *                   &lt;element name="timeZoneInfo" type="{http://zakupki.gov.ru/eruz/common/1}timeZoneRef"/>
     *                   &lt;element name="isParticipant" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="isSubcontractor" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="filialContactInfo">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://zakupki.gov.ru/eruz/common/1}contactsType">
     *                 &lt;sequence>
     *                   &lt;element name="postAdress" type="{http://zakupki.gov.ru/eruz/base/1}text2000Type" minOccurs="0"/>
     *                   &lt;element name="url" type="{http://zakupki.gov.ru/eruz/base/1}hrefType" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="attachmentsInfo">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="consentDecisionsInfo" type="{http://zakupki.gov.ru/eruz/common/1}attachmentListType"/>
     *                   &lt;element name="foundingDocsCopyInfo" type="{http://zakupki.gov.ru/eruz/common/1}attachmentListType" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "filialLegalEntityRFDataInfo",
        "filialContactInfo",
        "attachmentsInfo"
    })
    public static class FilialInfo {

        @XmlElement(required = true)
        protected FilialLegalEntityRFType.FilialInfo.FilialLegalEntityRFDataInfo filialLegalEntityRFDataInfo;
        @XmlElement(required = true)
        protected FilialLegalEntityRFType.FilialInfo.FilialContactInfo filialContactInfo;
        @XmlElement(required = true)
        protected FilialLegalEntityRFType.FilialInfo.AttachmentsInfo attachmentsInfo;

        /**
         * Gets the value of the filialLegalEntityRFDataInfo property.
         * 
         * @return
         *     possible object is
         *     {@link FilialLegalEntityRFType.FilialInfo.FilialLegalEntityRFDataInfo }
         *     
         */
        public FilialLegalEntityRFType.FilialInfo.FilialLegalEntityRFDataInfo getFilialLegalEntityRFDataInfo() {
            return filialLegalEntityRFDataInfo;
        }

        /**
         * Sets the value of the filialLegalEntityRFDataInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link FilialLegalEntityRFType.FilialInfo.FilialLegalEntityRFDataInfo }
         *     
         */
        public void setFilialLegalEntityRFDataInfo(FilialLegalEntityRFType.FilialInfo.FilialLegalEntityRFDataInfo value) {
            this.filialLegalEntityRFDataInfo = value;
        }

        /**
         * Gets the value of the filialContactInfo property.
         * 
         * @return
         *     possible object is
         *     {@link FilialLegalEntityRFType.FilialInfo.FilialContactInfo }
         *     
         */
        public FilialLegalEntityRFType.FilialInfo.FilialContactInfo getFilialContactInfo() {
            return filialContactInfo;
        }

        /**
         * Sets the value of the filialContactInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link FilialLegalEntityRFType.FilialInfo.FilialContactInfo }
         *     
         */
        public void setFilialContactInfo(FilialLegalEntityRFType.FilialInfo.FilialContactInfo value) {
            this.filialContactInfo = value;
        }

        /**
         * Gets the value of the attachmentsInfo property.
         * 
         * @return
         *     possible object is
         *     {@link FilialLegalEntityRFType.FilialInfo.AttachmentsInfo }
         *     
         */
        public FilialLegalEntityRFType.FilialInfo.AttachmentsInfo getAttachmentsInfo() {
            return attachmentsInfo;
        }

        /**
         * Sets the value of the attachmentsInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link FilialLegalEntityRFType.FilialInfo.AttachmentsInfo }
         *     
         */
        public void setAttachmentsInfo(FilialLegalEntityRFType.FilialInfo.AttachmentsInfo value) {
            this.attachmentsInfo = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="consentDecisionsInfo" type="{http://zakupki.gov.ru/eruz/common/1}attachmentListType"/>
         *         &lt;element name="foundingDocsCopyInfo" type="{http://zakupki.gov.ru/eruz/common/1}attachmentListType" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "consentDecisionsInfo",
            "foundingDocsCopyInfo"
        })
        public static class AttachmentsInfo {

            @XmlElement(required = true)
            protected AttachmentListType consentDecisionsInfo;
            protected AttachmentListType foundingDocsCopyInfo;

            /**
             * Gets the value of the consentDecisionsInfo property.
             * 
             * @return
             *     possible object is
             *     {@link AttachmentListType }
             *     
             */
            public AttachmentListType getConsentDecisionsInfo() {
                return consentDecisionsInfo;
            }

            /**
             * Sets the value of the consentDecisionsInfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link AttachmentListType }
             *     
             */
            public void setConsentDecisionsInfo(AttachmentListType value) {
                this.consentDecisionsInfo = value;
            }

            /**
             * Gets the value of the foundingDocsCopyInfo property.
             * 
             * @return
             *     possible object is
             *     {@link AttachmentListType }
             *     
             */
            public AttachmentListType getFoundingDocsCopyInfo() {
                return foundingDocsCopyInfo;
            }

            /**
             * Sets the value of the foundingDocsCopyInfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link AttachmentListType }
             *     
             */
            public void setFoundingDocsCopyInfo(AttachmentListType value) {
                this.foundingDocsCopyInfo = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://zakupki.gov.ru/eruz/common/1}contactsType">
         *       &lt;sequence>
         *         &lt;element name="postAdress" type="{http://zakupki.gov.ru/eruz/base/1}text2000Type" minOccurs="0"/>
         *         &lt;element name="url" type="{http://zakupki.gov.ru/eruz/base/1}hrefType" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "postAdress",
            "url"
        })
        public static class FilialContactInfo
            extends ContactsType
        {

            protected String postAdress;
            protected String url;

            /**
             * Gets the value of the postAdress property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPostAdress() {
                return postAdress;
            }

            /**
             * Sets the value of the postAdress property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPostAdress(String value) {
                this.postAdress = value;
            }

            /**
             * Gets the value of the url property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUrl() {
                return url;
            }

            /**
             * Sets the value of the url property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUrl(String value) {
                this.url = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="KPP" type="{http://zakupki.gov.ru/eruz/base/1}kppType"/>
         *         &lt;element name="fullName" type="{http://zakupki.gov.ru/eruz/base/1}text1000Type"/>
         *         &lt;element name="factAdressInfo" type="{http://zakupki.gov.ru/eruz/types/1}factAdressType"/>
         *         &lt;element name="maxPrice" type="{http://zakupki.gov.ru/eruz/base/1}moneyMaxLengthToPoint21Type"/>
         *         &lt;element name="timeZoneInfo" type="{http://zakupki.gov.ru/eruz/common/1}timeZoneRef"/>
         *         &lt;element name="isParticipant" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="isSubcontractor" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "kpp",
            "fullName",
            "factAdressInfo",
            "maxPrice",
            "timeZoneInfo",
            "isParticipant",
            "isSubcontractor"
        })
        public static class FilialLegalEntityRFDataInfo {

            @XmlElement(name = "KPP", required = true)
            protected String kpp;
            @XmlElement(required = true)
            protected String fullName;
            @XmlElement(required = true)
            protected FactAdressType factAdressInfo;
            @XmlElement(required = true)
            protected String maxPrice;
            @XmlElement(required = true)
            protected TimeZoneRef timeZoneInfo;
            protected boolean isParticipant;
            protected boolean isSubcontractor;

            /**
             * Gets the value of the kpp property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getKPP() {
                return kpp;
            }

            /**
             * Sets the value of the kpp property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setKPP(String value) {
                this.kpp = value;
            }

            /**
             * Gets the value of the fullName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFullName() {
                return fullName;
            }

            /**
             * Sets the value of the fullName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFullName(String value) {
                this.fullName = value;
            }

            /**
             * Gets the value of the factAdressInfo property.
             * 
             * @return
             *     possible object is
             *     {@link FactAdressType }
             *     
             */
            public FactAdressType getFactAdressInfo() {
                return factAdressInfo;
            }

            /**
             * Sets the value of the factAdressInfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link FactAdressType }
             *     
             */
            public void setFactAdressInfo(FactAdressType value) {
                this.factAdressInfo = value;
            }

            /**
             * Gets the value of the maxPrice property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMaxPrice() {
                return maxPrice;
            }

            /**
             * Sets the value of the maxPrice property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMaxPrice(String value) {
                this.maxPrice = value;
            }

            /**
             * Gets the value of the timeZoneInfo property.
             * 
             * @return
             *     possible object is
             *     {@link TimeZoneRef }
             *     
             */
            public TimeZoneRef getTimeZoneInfo() {
                return timeZoneInfo;
            }

            /**
             * Sets the value of the timeZoneInfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link TimeZoneRef }
             *     
             */
            public void setTimeZoneInfo(TimeZoneRef value) {
                this.timeZoneInfo = value;
            }

            /**
             * Gets the value of the isParticipant property.
             * 
             */
            public boolean isIsParticipant() {
                return isParticipant;
            }

            /**
             * Sets the value of the isParticipant property.
             * 
             */
            public void setIsParticipant(boolean value) {
                this.isParticipant = value;
            }

            /**
             * Gets the value of the isSubcontractor property.
             * 
             */
            public boolean isIsSubcontractor() {
                return isSubcontractor;
            }

            /**
             * Sets the value of the isSubcontractor property.
             * 
             */
            public void setIsSubcontractor(boolean value) {
                this.isSubcontractor = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="legalEntityRFDataInfo">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://zakupki.gov.ru/eruz/types/1}legalEntityRFDataType">
     *                 &lt;sequence>
     *                   &lt;element name="OKOPF" type="{http://zakupki.gov.ru/eruz/common/1}OKOPFRef" minOccurs="0"/>
     *                   &lt;element name="majorTaxPayerKPP" type="{http://zakupki.gov.ru/eruz/base/1}kppType" minOccurs="0"/>
     *                   &lt;element name="EGRULStatementInfo" type="{http://zakupki.gov.ru/eruz/common/1}attachmentType" minOccurs="0"/>
     *                   &lt;element name="registryNum" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://zakupki.gov.ru/eruz/base/1>eruzRegistryNumType">
     *                           &lt;attribute name="isArchived" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="managingOrganization" type="{http://zakupki.gov.ru/eruz/types/1}managingOrganizationType" minOccurs="0"/>
     *         &lt;element name="informationPersons" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="informationPersonInfo" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="nameInfo" type="{http://zakupki.gov.ru/eruz/common/1}personType"/>
     *                             &lt;element name="position" type="{http://zakupki.gov.ru/eruz/base/1}positionType"/>
     *                             &lt;element name="identityDocInfo" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;choice>
     *                                       &lt;element name="passportRFInfo" type="{http://zakupki.gov.ru/eruz/common/1}passportRFType"/>
     *                                       &lt;element name="internationalPassportRFInfo" type="{http://zakupki.gov.ru/eruz/common/1}internationalPassportRFType"/>
     *                                       &lt;element name="passportForeignInfo" type="{http://zakupki.gov.ru/eruz/types/1}passportForeignType"/>
     *                                       &lt;element name="sojournPermitInfo" type="{http://zakupki.gov.ru/eruz/types/1}sojournPermitType"/>
     *                                       &lt;element name="permamentResidencyInfo" type="{http://zakupki.gov.ru/eruz/types/1}permamentResidencyType"/>
     *                                     &lt;/choice>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="INN" type="{http://zakupki.gov.ru/eruz/base/1}innIndividualType" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "legalEntityRFDataInfo",
        "managingOrganization",
        "informationPersons"
    })
    public static class LegalEntityInfo {

        @XmlElement(required = true)
        protected FilialLegalEntityRFType.LegalEntityInfo.LegalEntityRFDataInfo legalEntityRFDataInfo;
        protected ManagingOrganizationType managingOrganization;
        protected FilialLegalEntityRFType.LegalEntityInfo.InformationPersons informationPersons;

        /**
         * Gets the value of the legalEntityRFDataInfo property.
         * 
         * @return
         *     possible object is
         *     {@link FilialLegalEntityRFType.LegalEntityInfo.LegalEntityRFDataInfo }
         *     
         */
        public FilialLegalEntityRFType.LegalEntityInfo.LegalEntityRFDataInfo getLegalEntityRFDataInfo() {
            return legalEntityRFDataInfo;
        }

        /**
         * Sets the value of the legalEntityRFDataInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link FilialLegalEntityRFType.LegalEntityInfo.LegalEntityRFDataInfo }
         *     
         */
        public void setLegalEntityRFDataInfo(FilialLegalEntityRFType.LegalEntityInfo.LegalEntityRFDataInfo value) {
            this.legalEntityRFDataInfo = value;
        }

        /**
         * Gets the value of the managingOrganization property.
         * 
         * @return
         *     possible object is
         *     {@link ManagingOrganizationType }
         *     
         */
        public ManagingOrganizationType getManagingOrganization() {
            return managingOrganization;
        }

        /**
         * Sets the value of the managingOrganization property.
         * 
         * @param value
         *     allowed object is
         *     {@link ManagingOrganizationType }
         *     
         */
        public void setManagingOrganization(ManagingOrganizationType value) {
            this.managingOrganization = value;
        }

        /**
         * Gets the value of the informationPersons property.
         * 
         * @return
         *     possible object is
         *     {@link FilialLegalEntityRFType.LegalEntityInfo.InformationPersons }
         *     
         */
        public FilialLegalEntityRFType.LegalEntityInfo.InformationPersons getInformationPersons() {
            return informationPersons;
        }

        /**
         * Sets the value of the informationPersons property.
         * 
         * @param value
         *     allowed object is
         *     {@link FilialLegalEntityRFType.LegalEntityInfo.InformationPersons }
         *     
         */
        public void setInformationPersons(FilialLegalEntityRFType.LegalEntityInfo.InformationPersons value) {
            this.informationPersons = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="informationPersonInfo" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="nameInfo" type="{http://zakupki.gov.ru/eruz/common/1}personType"/>
         *                   &lt;element name="position" type="{http://zakupki.gov.ru/eruz/base/1}positionType"/>
         *                   &lt;element name="identityDocInfo" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;choice>
         *                             &lt;element name="passportRFInfo" type="{http://zakupki.gov.ru/eruz/common/1}passportRFType"/>
         *                             &lt;element name="internationalPassportRFInfo" type="{http://zakupki.gov.ru/eruz/common/1}internationalPassportRFType"/>
         *                             &lt;element name="passportForeignInfo" type="{http://zakupki.gov.ru/eruz/types/1}passportForeignType"/>
         *                             &lt;element name="sojournPermitInfo" type="{http://zakupki.gov.ru/eruz/types/1}sojournPermitType"/>
         *                             &lt;element name="permamentResidencyInfo" type="{http://zakupki.gov.ru/eruz/types/1}permamentResidencyType"/>
         *                           &lt;/choice>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="INN" type="{http://zakupki.gov.ru/eruz/base/1}innIndividualType" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "informationPersonInfo"
        })
        public static class InformationPersons {

            @XmlElement(required = true)
            protected List<FilialLegalEntityRFType.LegalEntityInfo.InformationPersons.InformationPersonInfo> informationPersonInfo;

            /**
             * Gets the value of the informationPersonInfo property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the informationPersonInfo property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getInformationPersonInfo().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link FilialLegalEntityRFType.LegalEntityInfo.InformationPersons.InformationPersonInfo }
             * 
             * 
             */
            public List<FilialLegalEntityRFType.LegalEntityInfo.InformationPersons.InformationPersonInfo> getInformationPersonInfo() {
                if (informationPersonInfo == null) {
                    informationPersonInfo = new ArrayList<FilialLegalEntityRFType.LegalEntityInfo.InformationPersons.InformationPersonInfo>();
                }
                return this.informationPersonInfo;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="nameInfo" type="{http://zakupki.gov.ru/eruz/common/1}personType"/>
             *         &lt;element name="position" type="{http://zakupki.gov.ru/eruz/base/1}positionType"/>
             *         &lt;element name="identityDocInfo" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;choice>
             *                   &lt;element name="passportRFInfo" type="{http://zakupki.gov.ru/eruz/common/1}passportRFType"/>
             *                   &lt;element name="internationalPassportRFInfo" type="{http://zakupki.gov.ru/eruz/common/1}internationalPassportRFType"/>
             *                   &lt;element name="passportForeignInfo" type="{http://zakupki.gov.ru/eruz/types/1}passportForeignType"/>
             *                   &lt;element name="sojournPermitInfo" type="{http://zakupki.gov.ru/eruz/types/1}sojournPermitType"/>
             *                   &lt;element name="permamentResidencyInfo" type="{http://zakupki.gov.ru/eruz/types/1}permamentResidencyType"/>
             *                 &lt;/choice>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="INN" type="{http://zakupki.gov.ru/eruz/base/1}innIndividualType" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "nameInfo",
                "position",
                "identityDocInfo",
                "inn"
            })
            public static class InformationPersonInfo {

                @XmlElement(required = true)
                protected PersonType nameInfo;
                @XmlElement(required = true)
                protected String position;
                protected FilialLegalEntityRFType.LegalEntityInfo.InformationPersons.InformationPersonInfo.IdentityDocInfo identityDocInfo;
                @XmlElement(name = "INN")
                protected String inn;

                /**
                 * Gets the value of the nameInfo property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link PersonType }
                 *     
                 */
                public PersonType getNameInfo() {
                    return nameInfo;
                }

                /**
                 * Sets the value of the nameInfo property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link PersonType }
                 *     
                 */
                public void setNameInfo(PersonType value) {
                    this.nameInfo = value;
                }

                /**
                 * Gets the value of the position property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPosition() {
                    return position;
                }

                /**
                 * Sets the value of the position property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPosition(String value) {
                    this.position = value;
                }

                /**
                 * Gets the value of the identityDocInfo property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link FilialLegalEntityRFType.LegalEntityInfo.InformationPersons.InformationPersonInfo.IdentityDocInfo }
                 *     
                 */
                public FilialLegalEntityRFType.LegalEntityInfo.InformationPersons.InformationPersonInfo.IdentityDocInfo getIdentityDocInfo() {
                    return identityDocInfo;
                }

                /**
                 * Sets the value of the identityDocInfo property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link FilialLegalEntityRFType.LegalEntityInfo.InformationPersons.InformationPersonInfo.IdentityDocInfo }
                 *     
                 */
                public void setIdentityDocInfo(FilialLegalEntityRFType.LegalEntityInfo.InformationPersons.InformationPersonInfo.IdentityDocInfo value) {
                    this.identityDocInfo = value;
                }

                /**
                 * Gets the value of the inn property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getINN() {
                    return inn;
                }

                /**
                 * Sets the value of the inn property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setINN(String value) {
                    this.inn = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;choice>
                 *         &lt;element name="passportRFInfo" type="{http://zakupki.gov.ru/eruz/common/1}passportRFType"/>
                 *         &lt;element name="internationalPassportRFInfo" type="{http://zakupki.gov.ru/eruz/common/1}internationalPassportRFType"/>
                 *         &lt;element name="passportForeignInfo" type="{http://zakupki.gov.ru/eruz/types/1}passportForeignType"/>
                 *         &lt;element name="sojournPermitInfo" type="{http://zakupki.gov.ru/eruz/types/1}sojournPermitType"/>
                 *         &lt;element name="permamentResidencyInfo" type="{http://zakupki.gov.ru/eruz/types/1}permamentResidencyType"/>
                 *       &lt;/choice>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "passportRFInfo",
                    "internationalPassportRFInfo",
                    "passportForeignInfo",
                    "sojournPermitInfo",
                    "permamentResidencyInfo"
                })
                public static class IdentityDocInfo {

                    protected PassportRFType passportRFInfo;
                    protected InternationalPassportRFType internationalPassportRFInfo;
                    protected PassportForeignType passportForeignInfo;
                    protected SojournPermitType sojournPermitInfo;
                    protected PermamentResidencyType permamentResidencyInfo;

                    /**
                     * Gets the value of the passportRFInfo property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link PassportRFType }
                     *     
                     */
                    public PassportRFType getPassportRFInfo() {
                        return passportRFInfo;
                    }

                    /**
                     * Sets the value of the passportRFInfo property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link PassportRFType }
                     *     
                     */
                    public void setPassportRFInfo(PassportRFType value) {
                        this.passportRFInfo = value;
                    }

                    /**
                     * Gets the value of the internationalPassportRFInfo property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link InternationalPassportRFType }
                     *     
                     */
                    public InternationalPassportRFType getInternationalPassportRFInfo() {
                        return internationalPassportRFInfo;
                    }

                    /**
                     * Sets the value of the internationalPassportRFInfo property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link InternationalPassportRFType }
                     *     
                     */
                    public void setInternationalPassportRFInfo(InternationalPassportRFType value) {
                        this.internationalPassportRFInfo = value;
                    }

                    /**
                     * Gets the value of the passportForeignInfo property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link PassportForeignType }
                     *     
                     */
                    public PassportForeignType getPassportForeignInfo() {
                        return passportForeignInfo;
                    }

                    /**
                     * Sets the value of the passportForeignInfo property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link PassportForeignType }
                     *     
                     */
                    public void setPassportForeignInfo(PassportForeignType value) {
                        this.passportForeignInfo = value;
                    }

                    /**
                     * Gets the value of the sojournPermitInfo property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link SojournPermitType }
                     *     
                     */
                    public SojournPermitType getSojournPermitInfo() {
                        return sojournPermitInfo;
                    }

                    /**
                     * Sets the value of the sojournPermitInfo property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link SojournPermitType }
                     *     
                     */
                    public void setSojournPermitInfo(SojournPermitType value) {
                        this.sojournPermitInfo = value;
                    }

                    /**
                     * Gets the value of the permamentResidencyInfo property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link PermamentResidencyType }
                     *     
                     */
                    public PermamentResidencyType getPermamentResidencyInfo() {
                        return permamentResidencyInfo;
                    }

                    /**
                     * Sets the value of the permamentResidencyInfo property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link PermamentResidencyType }
                     *     
                     */
                    public void setPermamentResidencyInfo(PermamentResidencyType value) {
                        this.permamentResidencyInfo = value;
                    }

                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://zakupki.gov.ru/eruz/types/1}legalEntityRFDataType">
         *       &lt;sequence>
         *         &lt;element name="OKOPF" type="{http://zakupki.gov.ru/eruz/common/1}OKOPFRef" minOccurs="0"/>
         *         &lt;element name="majorTaxPayerKPP" type="{http://zakupki.gov.ru/eruz/base/1}kppType" minOccurs="0"/>
         *         &lt;element name="EGRULStatementInfo" type="{http://zakupki.gov.ru/eruz/common/1}attachmentType" minOccurs="0"/>
         *         &lt;element name="registryNum" minOccurs="0">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://zakupki.gov.ru/eruz/base/1>eruzRegistryNumType">
         *                 &lt;attribute name="isArchived" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "okopf",
            "majorTaxPayerKPP",
            "egrulStatementInfo",
            "registryNum"
        })
        public static class LegalEntityRFDataInfo
            extends LegalEntityRFDataType
        {

            @XmlElement(name = "OKOPF")
            protected OKOPFRef okopf;
            protected String majorTaxPayerKPP;
            @XmlElement(name = "EGRULStatementInfo")
            protected AttachmentType egrulStatementInfo;
            protected FilialLegalEntityRFType.LegalEntityInfo.LegalEntityRFDataInfo.RegistryNum registryNum;

            /**
             * Gets the value of the okopf property.
             * 
             * @return
             *     possible object is
             *     {@link OKOPFRef }
             *     
             */
            public OKOPFRef getOKOPF() {
                return okopf;
            }

            /**
             * Sets the value of the okopf property.
             * 
             * @param value
             *     allowed object is
             *     {@link OKOPFRef }
             *     
             */
            public void setOKOPF(OKOPFRef value) {
                this.okopf = value;
            }

            /**
             * Gets the value of the majorTaxPayerKPP property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMajorTaxPayerKPP() {
                return majorTaxPayerKPP;
            }

            /**
             * Sets the value of the majorTaxPayerKPP property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMajorTaxPayerKPP(String value) {
                this.majorTaxPayerKPP = value;
            }

            /**
             * Gets the value of the egrulStatementInfo property.
             * 
             * @return
             *     possible object is
             *     {@link AttachmentType }
             *     
             */
            public AttachmentType getEGRULStatementInfo() {
                return egrulStatementInfo;
            }

            /**
             * Sets the value of the egrulStatementInfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link AttachmentType }
             *     
             */
            public void setEGRULStatementInfo(AttachmentType value) {
                this.egrulStatementInfo = value;
            }

            /**
             * Gets the value of the registryNum property.
             * 
             * @return
             *     possible object is
             *     {@link FilialLegalEntityRFType.LegalEntityInfo.LegalEntityRFDataInfo.RegistryNum }
             *     
             */
            public FilialLegalEntityRFType.LegalEntityInfo.LegalEntityRFDataInfo.RegistryNum getRegistryNum() {
                return registryNum;
            }

            /**
             * Sets the value of the registryNum property.
             * 
             * @param value
             *     allowed object is
             *     {@link FilialLegalEntityRFType.LegalEntityInfo.LegalEntityRFDataInfo.RegistryNum }
             *     
             */
            public void setRegistryNum(FilialLegalEntityRFType.LegalEntityInfo.LegalEntityRFDataInfo.RegistryNum value) {
                this.registryNum = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://zakupki.gov.ru/eruz/base/1>eruzRegistryNumType">
             *       &lt;attribute name="isArchived" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class RegistryNum {

                @XmlValue
                protected String value;
                @XmlAttribute(name = "isArchived", required = true)
                protected boolean isArchived;

                /**
                 * Тип: Номер реестровой записи в ЕРУЗ
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the isArchived property.
                 * 
                 */
                public boolean isIsArchived() {
                    return isArchived;
                }

                /**
                 * Sets the value of the isArchived property.
                 * 
                 */
                public void setIsArchived(boolean value) {
                    this.isArchived = value;
                }

            }

        }

    }

}
