//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.02 at 03:51:32 PM MSK 
//


package ru.gov.zakupki.eruz.types._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import ru.gov.zakupki.eruz.common._1.AttachmentListType;
import ru.gov.zakupki.eruz.common._1.AttachmentType;
import ru.gov.zakupki.eruz.common._1.ContactsType;
import ru.gov.zakupki.eruz.common._1.OKSMRef;
import ru.gov.zakupki.eruz.common._1.PersonType;
import ru.gov.zakupki.eruz.common._1.TimeZoneRef;


/**
 * Тип: Физическое лицо иностранного государства
 * 
 * <p>Java class for individualPersonForeignStateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="individualPersonForeignStateType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="individualPersonForeignStateDataInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="nameInfo" type="{http://zakupki.gov.ru/eruz/common/1}personType"/>
 *                   &lt;element name="nameLatInfo" type="{http://zakupki.gov.ru/eruz/common/1}personType" minOccurs="0"/>
 *                   &lt;element name="taxPayerCode" type="{http://zakupki.gov.ru/eruz/base/1}taxPayerCode"/>
 *                   &lt;element name="countryInfo" type="{http://zakupki.gov.ru/eruz/common/1}OKSMRef" minOccurs="0"/>
 *                   &lt;element name="factAdress" type="{http://zakupki.gov.ru/eruz/base/1}text2000Type" minOccurs="0"/>
 *                   &lt;element name="identityDocInfo">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice>
 *                             &lt;element name="passportForeignInfo" type="{http://zakupki.gov.ru/eruz/types/1}passportForeignType"/>
 *                             &lt;element name="sojournPermitInfo" type="{http://zakupki.gov.ru/eruz/types/1}sojournPermitType"/>
 *                             &lt;element name="permamentResidencyInfo" type="{http://zakupki.gov.ru/eruz/types/1}permamentResidencyType"/>
 *                           &lt;/choice>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="timeZoneInfo" type="{http://zakupki.gov.ru/eruz/common/1}timeZoneRef"/>
 *                   &lt;element name="taxRegDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                   &lt;element name="IPInfo" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="INN" type="{http://zakupki.gov.ru/eruz/base/1}innIndividualType"/>
 *                             &lt;element name="OGRNIP" type="{http://zakupki.gov.ru/eruz/base/1}OGRNIPCodeType"/>
 *                             &lt;element name="regDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                             &lt;element name="EGRIPStatementInfo" type="{http://zakupki.gov.ru/eruz/common/1}attachmentType"/>
 *                             &lt;element name="MSPSign" type="{http://zakupki.gov.ru/eruz/types/1}MSPSignType" minOccurs="0"/>
 *                             &lt;element name="factAdressInfo" type="{http://zakupki.gov.ru/eruz/types/1}factAdressType" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="isParticipant" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="contactInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://zakupki.gov.ru/eruz/common/1}contactsType">
 *                 &lt;sequence>
 *                   &lt;element name="postAdress" type="{http://zakupki.gov.ru/eruz/base/1}text2000Type"/>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="attachmentsInfo" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="passportCopyInfo" type="{http://zakupki.gov.ru/eruz/common/1}attachmentListType" minOccurs="0"/>
 *                   &lt;element name="gosRegPersonInfo" type="{http://zakupki.gov.ru/eruz/common/1}attachmentListType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "individualPersonForeignStateType", propOrder = {
    "individualPersonForeignStateDataInfo",
    "contactInfo",
    "attachmentsInfo"
})
public class IndividualPersonForeignStateType {

    @XmlElement(required = true)
    protected IndividualPersonForeignStateType.IndividualPersonForeignStateDataInfo individualPersonForeignStateDataInfo;
    @XmlElement(required = true)
    protected IndividualPersonForeignStateType.ContactInfo contactInfo;
    protected IndividualPersonForeignStateType.AttachmentsInfo attachmentsInfo;

    /**
     * Gets the value of the individualPersonForeignStateDataInfo property.
     * 
     * @return
     *     possible object is
     *     {@link IndividualPersonForeignStateType.IndividualPersonForeignStateDataInfo }
     *     
     */
    public IndividualPersonForeignStateType.IndividualPersonForeignStateDataInfo getIndividualPersonForeignStateDataInfo() {
        return individualPersonForeignStateDataInfo;
    }

    /**
     * Sets the value of the individualPersonForeignStateDataInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndividualPersonForeignStateType.IndividualPersonForeignStateDataInfo }
     *     
     */
    public void setIndividualPersonForeignStateDataInfo(IndividualPersonForeignStateType.IndividualPersonForeignStateDataInfo value) {
        this.individualPersonForeignStateDataInfo = value;
    }

    /**
     * Gets the value of the contactInfo property.
     * 
     * @return
     *     possible object is
     *     {@link IndividualPersonForeignStateType.ContactInfo }
     *     
     */
    public IndividualPersonForeignStateType.ContactInfo getContactInfo() {
        return contactInfo;
    }

    /**
     * Sets the value of the contactInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndividualPersonForeignStateType.ContactInfo }
     *     
     */
    public void setContactInfo(IndividualPersonForeignStateType.ContactInfo value) {
        this.contactInfo = value;
    }

    /**
     * Gets the value of the attachmentsInfo property.
     * 
     * @return
     *     possible object is
     *     {@link IndividualPersonForeignStateType.AttachmentsInfo }
     *     
     */
    public IndividualPersonForeignStateType.AttachmentsInfo getAttachmentsInfo() {
        return attachmentsInfo;
    }

    /**
     * Sets the value of the attachmentsInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndividualPersonForeignStateType.AttachmentsInfo }
     *     
     */
    public void setAttachmentsInfo(IndividualPersonForeignStateType.AttachmentsInfo value) {
        this.attachmentsInfo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="passportCopyInfo" type="{http://zakupki.gov.ru/eruz/common/1}attachmentListType" minOccurs="0"/>
     *         &lt;element name="gosRegPersonInfo" type="{http://zakupki.gov.ru/eruz/common/1}attachmentListType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "passportCopyInfo",
        "gosRegPersonInfo"
    })
    public static class AttachmentsInfo {

        protected AttachmentListType passportCopyInfo;
        protected AttachmentListType gosRegPersonInfo;

        /**
         * Gets the value of the passportCopyInfo property.
         * 
         * @return
         *     possible object is
         *     {@link AttachmentListType }
         *     
         */
        public AttachmentListType getPassportCopyInfo() {
            return passportCopyInfo;
        }

        /**
         * Sets the value of the passportCopyInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link AttachmentListType }
         *     
         */
        public void setPassportCopyInfo(AttachmentListType value) {
            this.passportCopyInfo = value;
        }

        /**
         * Gets the value of the gosRegPersonInfo property.
         * 
         * @return
         *     possible object is
         *     {@link AttachmentListType }
         *     
         */
        public AttachmentListType getGosRegPersonInfo() {
            return gosRegPersonInfo;
        }

        /**
         * Sets the value of the gosRegPersonInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link AttachmentListType }
         *     
         */
        public void setGosRegPersonInfo(AttachmentListType value) {
            this.gosRegPersonInfo = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://zakupki.gov.ru/eruz/common/1}contactsType">
     *       &lt;sequence>
     *         &lt;element name="postAdress" type="{http://zakupki.gov.ru/eruz/base/1}text2000Type"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "postAdress"
    })
    public static class ContactInfo
        extends ContactsType
    {

        @XmlElement(required = true)
        protected String postAdress;

        /**
         * Gets the value of the postAdress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPostAdress() {
            return postAdress;
        }

        /**
         * Sets the value of the postAdress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPostAdress(String value) {
            this.postAdress = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="nameInfo" type="{http://zakupki.gov.ru/eruz/common/1}personType"/>
     *         &lt;element name="nameLatInfo" type="{http://zakupki.gov.ru/eruz/common/1}personType" minOccurs="0"/>
     *         &lt;element name="taxPayerCode" type="{http://zakupki.gov.ru/eruz/base/1}taxPayerCode"/>
     *         &lt;element name="countryInfo" type="{http://zakupki.gov.ru/eruz/common/1}OKSMRef" minOccurs="0"/>
     *         &lt;element name="factAdress" type="{http://zakupki.gov.ru/eruz/base/1}text2000Type" minOccurs="0"/>
     *         &lt;element name="identityDocInfo">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice>
     *                   &lt;element name="passportForeignInfo" type="{http://zakupki.gov.ru/eruz/types/1}passportForeignType"/>
     *                   &lt;element name="sojournPermitInfo" type="{http://zakupki.gov.ru/eruz/types/1}sojournPermitType"/>
     *                   &lt;element name="permamentResidencyInfo" type="{http://zakupki.gov.ru/eruz/types/1}permamentResidencyType"/>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="timeZoneInfo" type="{http://zakupki.gov.ru/eruz/common/1}timeZoneRef"/>
     *         &lt;element name="taxRegDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *         &lt;element name="IPInfo" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="INN" type="{http://zakupki.gov.ru/eruz/base/1}innIndividualType"/>
     *                   &lt;element name="OGRNIP" type="{http://zakupki.gov.ru/eruz/base/1}OGRNIPCodeType"/>
     *                   &lt;element name="regDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *                   &lt;element name="EGRIPStatementInfo" type="{http://zakupki.gov.ru/eruz/common/1}attachmentType"/>
     *                   &lt;element name="MSPSign" type="{http://zakupki.gov.ru/eruz/types/1}MSPSignType" minOccurs="0"/>
     *                   &lt;element name="factAdressInfo" type="{http://zakupki.gov.ru/eruz/types/1}factAdressType" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="isParticipant" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nameInfo",
        "nameLatInfo",
        "taxPayerCode",
        "countryInfo",
        "factAdress",
        "identityDocInfo",
        "timeZoneInfo",
        "taxRegDate",
        "ipInfo",
        "isParticipant"
    })
    public static class IndividualPersonForeignStateDataInfo {

        @XmlElement(required = true)
        protected PersonType nameInfo;
        protected PersonType nameLatInfo;
        @XmlElement(required = true)
        protected String taxPayerCode;
        protected OKSMRef countryInfo;
        protected String factAdress;
        @XmlElement(required = true)
        protected IndividualPersonForeignStateType.IndividualPersonForeignStateDataInfo.IdentityDocInfo identityDocInfo;
        @XmlElement(required = true)
        protected TimeZoneRef timeZoneInfo;
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar taxRegDate;
        @XmlElement(name = "IPInfo")
        protected IndividualPersonForeignStateType.IndividualPersonForeignStateDataInfo.IPInfo ipInfo;
        protected boolean isParticipant;

        /**
         * Gets the value of the nameInfo property.
         * 
         * @return
         *     possible object is
         *     {@link PersonType }
         *     
         */
        public PersonType getNameInfo() {
            return nameInfo;
        }

        /**
         * Sets the value of the nameInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link PersonType }
         *     
         */
        public void setNameInfo(PersonType value) {
            this.nameInfo = value;
        }

        /**
         * Gets the value of the nameLatInfo property.
         * 
         * @return
         *     possible object is
         *     {@link PersonType }
         *     
         */
        public PersonType getNameLatInfo() {
            return nameLatInfo;
        }

        /**
         * Sets the value of the nameLatInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link PersonType }
         *     
         */
        public void setNameLatInfo(PersonType value) {
            this.nameLatInfo = value;
        }

        /**
         * Gets the value of the taxPayerCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTaxPayerCode() {
            return taxPayerCode;
        }

        /**
         * Sets the value of the taxPayerCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTaxPayerCode(String value) {
            this.taxPayerCode = value;
        }

        /**
         * Gets the value of the countryInfo property.
         * 
         * @return
         *     possible object is
         *     {@link OKSMRef }
         *     
         */
        public OKSMRef getCountryInfo() {
            return countryInfo;
        }

        /**
         * Sets the value of the countryInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link OKSMRef }
         *     
         */
        public void setCountryInfo(OKSMRef value) {
            this.countryInfo = value;
        }

        /**
         * Gets the value of the factAdress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFactAdress() {
            return factAdress;
        }

        /**
         * Sets the value of the factAdress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFactAdress(String value) {
            this.factAdress = value;
        }

        /**
         * Gets the value of the identityDocInfo property.
         * 
         * @return
         *     possible object is
         *     {@link IndividualPersonForeignStateType.IndividualPersonForeignStateDataInfo.IdentityDocInfo }
         *     
         */
        public IndividualPersonForeignStateType.IndividualPersonForeignStateDataInfo.IdentityDocInfo getIdentityDocInfo() {
            return identityDocInfo;
        }

        /**
         * Sets the value of the identityDocInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link IndividualPersonForeignStateType.IndividualPersonForeignStateDataInfo.IdentityDocInfo }
         *     
         */
        public void setIdentityDocInfo(IndividualPersonForeignStateType.IndividualPersonForeignStateDataInfo.IdentityDocInfo value) {
            this.identityDocInfo = value;
        }

        /**
         * Gets the value of the timeZoneInfo property.
         * 
         * @return
         *     possible object is
         *     {@link TimeZoneRef }
         *     
         */
        public TimeZoneRef getTimeZoneInfo() {
            return timeZoneInfo;
        }

        /**
         * Sets the value of the timeZoneInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link TimeZoneRef }
         *     
         */
        public void setTimeZoneInfo(TimeZoneRef value) {
            this.timeZoneInfo = value;
        }

        /**
         * Gets the value of the taxRegDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getTaxRegDate() {
            return taxRegDate;
        }

        /**
         * Sets the value of the taxRegDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setTaxRegDate(XMLGregorianCalendar value) {
            this.taxRegDate = value;
        }

        /**
         * Gets the value of the ipInfo property.
         * 
         * @return
         *     possible object is
         *     {@link IndividualPersonForeignStateType.IndividualPersonForeignStateDataInfo.IPInfo }
         *     
         */
        public IndividualPersonForeignStateType.IndividualPersonForeignStateDataInfo.IPInfo getIPInfo() {
            return ipInfo;
        }

        /**
         * Sets the value of the ipInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link IndividualPersonForeignStateType.IndividualPersonForeignStateDataInfo.IPInfo }
         *     
         */
        public void setIPInfo(IndividualPersonForeignStateType.IndividualPersonForeignStateDataInfo.IPInfo value) {
            this.ipInfo = value;
        }

        /**
         * Gets the value of the isParticipant property.
         * 
         */
        public boolean isIsParticipant() {
            return isParticipant;
        }

        /**
         * Sets the value of the isParticipant property.
         * 
         */
        public void setIsParticipant(boolean value) {
            this.isParticipant = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice>
         *         &lt;element name="passportForeignInfo" type="{http://zakupki.gov.ru/eruz/types/1}passportForeignType"/>
         *         &lt;element name="sojournPermitInfo" type="{http://zakupki.gov.ru/eruz/types/1}sojournPermitType"/>
         *         &lt;element name="permamentResidencyInfo" type="{http://zakupki.gov.ru/eruz/types/1}permamentResidencyType"/>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "passportForeignInfo",
            "sojournPermitInfo",
            "permamentResidencyInfo"
        })
        public static class IdentityDocInfo {

            protected PassportForeignType passportForeignInfo;
            protected SojournPermitType sojournPermitInfo;
            protected PermamentResidencyType permamentResidencyInfo;

            /**
             * Gets the value of the passportForeignInfo property.
             * 
             * @return
             *     possible object is
             *     {@link PassportForeignType }
             *     
             */
            public PassportForeignType getPassportForeignInfo() {
                return passportForeignInfo;
            }

            /**
             * Sets the value of the passportForeignInfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link PassportForeignType }
             *     
             */
            public void setPassportForeignInfo(PassportForeignType value) {
                this.passportForeignInfo = value;
            }

            /**
             * Gets the value of the sojournPermitInfo property.
             * 
             * @return
             *     possible object is
             *     {@link SojournPermitType }
             *     
             */
            public SojournPermitType getSojournPermitInfo() {
                return sojournPermitInfo;
            }

            /**
             * Sets the value of the sojournPermitInfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link SojournPermitType }
             *     
             */
            public void setSojournPermitInfo(SojournPermitType value) {
                this.sojournPermitInfo = value;
            }

            /**
             * Gets the value of the permamentResidencyInfo property.
             * 
             * @return
             *     possible object is
             *     {@link PermamentResidencyType }
             *     
             */
            public PermamentResidencyType getPermamentResidencyInfo() {
                return permamentResidencyInfo;
            }

            /**
             * Sets the value of the permamentResidencyInfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link PermamentResidencyType }
             *     
             */
            public void setPermamentResidencyInfo(PermamentResidencyType value) {
                this.permamentResidencyInfo = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="INN" type="{http://zakupki.gov.ru/eruz/base/1}innIndividualType"/>
         *         &lt;element name="OGRNIP" type="{http://zakupki.gov.ru/eruz/base/1}OGRNIPCodeType"/>
         *         &lt;element name="regDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
         *         &lt;element name="EGRIPStatementInfo" type="{http://zakupki.gov.ru/eruz/common/1}attachmentType"/>
         *         &lt;element name="MSPSign" type="{http://zakupki.gov.ru/eruz/types/1}MSPSignType" minOccurs="0"/>
         *         &lt;element name="factAdressInfo" type="{http://zakupki.gov.ru/eruz/types/1}factAdressType" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "inn",
            "ogrnip",
            "regDate",
            "egripStatementInfo",
            "mspSign",
            "factAdressInfo"
        })
        public static class IPInfo {

            @XmlElement(name = "INN", required = true)
            protected String inn;
            @XmlElement(name = "OGRNIP", required = true)
            protected String ogrnip;
            @XmlElement(required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar regDate;
            @XmlElement(name = "EGRIPStatementInfo", required = true)
            protected AttachmentType egripStatementInfo;
            @XmlElement(name = "MSPSign")
            @XmlSchemaType(name = "string")
            protected MSPSignType mspSign;
            protected FactAdressType factAdressInfo;

            /**
             * Gets the value of the inn property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getINN() {
                return inn;
            }

            /**
             * Sets the value of the inn property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setINN(String value) {
                this.inn = value;
            }

            /**
             * Gets the value of the ogrnip property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOGRNIP() {
                return ogrnip;
            }

            /**
             * Sets the value of the ogrnip property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOGRNIP(String value) {
                this.ogrnip = value;
            }

            /**
             * Gets the value of the regDate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getRegDate() {
                return regDate;
            }

            /**
             * Sets the value of the regDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setRegDate(XMLGregorianCalendar value) {
                this.regDate = value;
            }

            /**
             * Gets the value of the egripStatementInfo property.
             * 
             * @return
             *     possible object is
             *     {@link AttachmentType }
             *     
             */
            public AttachmentType getEGRIPStatementInfo() {
                return egripStatementInfo;
            }

            /**
             * Sets the value of the egripStatementInfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link AttachmentType }
             *     
             */
            public void setEGRIPStatementInfo(AttachmentType value) {
                this.egripStatementInfo = value;
            }

            /**
             * Gets the value of the mspSign property.
             * 
             * @return
             *     possible object is
             *     {@link MSPSignType }
             *     
             */
            public MSPSignType getMSPSign() {
                return mspSign;
            }

            /**
             * Sets the value of the mspSign property.
             * 
             * @param value
             *     allowed object is
             *     {@link MSPSignType }
             *     
             */
            public void setMSPSign(MSPSignType value) {
                this.mspSign = value;
            }

            /**
             * Gets the value of the factAdressInfo property.
             * 
             * @return
             *     possible object is
             *     {@link FactAdressType }
             *     
             */
            public FactAdressType getFactAdressInfo() {
                return factAdressInfo;
            }

            /**
             * Sets the value of the factAdressInfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link FactAdressType }
             *     
             */
            public void setFactAdressInfo(FactAdressType value) {
                this.factAdressInfo = value;
            }

        }

    }

}
