//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.02 at 03:51:32 PM MSK 
//


package ru.gov.zakupki.eruz.types._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import ru.gov.zakupki.eruz.common._1.AttachmentListType;
import ru.gov.zakupki.eruz.common._1.ContactsType;
import ru.gov.zakupki.eruz.common._1.InternationalPassportRFType;
import ru.gov.zakupki.eruz.common._1.OKVEDRef;
import ru.gov.zakupki.eruz.common._1.PassportRFType;
import ru.gov.zakupki.eruz.common._1.PersonType;
import ru.gov.zakupki.eruz.common._1.TimeZoneRef;


/**
 * Тип: Аккредитованный филиал или представительство иностранного юридического лица
 * 
 * <p>Java class for legalEntityForeignStateInRAFPType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="legalEntityForeignStateInRAFPType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="legalEntityForeignStateDataInfo" type="{http://zakupki.gov.ru/eruz/types/1}legalEntityForeignStateDataType"/>
 *         &lt;element name="filialLegalEntityForeignStateInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="filialLegalEntityForeignStateDataInfo">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="fullName" type="{http://zakupki.gov.ru/eruz/base/1}text1000Type"/>
 *                             &lt;element name="shortName" type="{http://zakupki.gov.ru/eruz/base/1}text510Type" minOccurs="0"/>
 *                             &lt;element name="INN" type="{http://zakupki.gov.ru/eruz/base/1}innOrganizationType"/>
 *                             &lt;element name="KPP" type="{http://zakupki.gov.ru/eruz/base/1}kppType"/>
 *                             &lt;element name="regDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                             &lt;element name="factAdressInfo" type="{http://zakupki.gov.ru/eruz/types/1}factAdressType"/>
 *                             &lt;element name="OKVEDs">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="OKVED" type="{http://zakupki.gov.ru/eruz/common/1}OKVEDRef" maxOccurs="unbounded"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="maxPrice" type="{http://zakupki.gov.ru/eruz/base/1}moneyMaxLengthToPoint21Type"/>
 *                             &lt;element name="timeZoneInfo" type="{http://zakupki.gov.ru/eruz/common/1}timeZoneRef"/>
 *                             &lt;element name="isParticipant" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="headInfo">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="nameInfo" type="{http://zakupki.gov.ru/eruz/common/1}personType"/>
 *                             &lt;element name="position" type="{http://zakupki.gov.ru/eruz/base/1}positionType"/>
 *                             &lt;element name="identityDocInfo" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;choice>
 *                                       &lt;element name="passportRFInfo" type="{http://zakupki.gov.ru/eruz/common/1}passportRFType"/>
 *                                       &lt;element name="internationalPassportRFInfo" type="{http://zakupki.gov.ru/eruz/common/1}internationalPassportRFType"/>
 *                                       &lt;element name="passportForeignInfo" type="{http://zakupki.gov.ru/eruz/types/1}passportForeignType"/>
 *                                       &lt;element name="sojournPermitInfo" type="{http://zakupki.gov.ru/eruz/types/1}sojournPermitType"/>
 *                                       &lt;element name="permamentResidencyInfo" type="{http://zakupki.gov.ru/eruz/types/1}permamentResidencyType"/>
 *                                     &lt;/choice>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="INN" type="{http://zakupki.gov.ru/eruz/base/1}innIndividualType" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="contactInfo">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{http://zakupki.gov.ru/eruz/common/1}contactsType">
 *                           &lt;sequence>
 *                             &lt;element name="postAdress" type="{http://zakupki.gov.ru/eruz/base/1}text2000Type"/>
 *                             &lt;element name="url" type="{http://zakupki.gov.ru/eruz/base/1}hrefType" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="attachmentsInfo">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="foundingDocLegalEntityInfo" type="{http://zakupki.gov.ru/eruz/common/1}attachmentListType"/>
 *                             &lt;element name="consentDecisionInfo" type="{http://zakupki.gov.ru/eruz/common/1}attachmentListType"/>
 *                             &lt;element name="govRegistrationLegalEntityDocInfo" type="{http://zakupki.gov.ru/eruz/common/1}attachmentListType"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "legalEntityForeignStateInRAFPType", propOrder = {
    "legalEntityForeignStateDataInfo",
    "filialLegalEntityForeignStateInfo"
})
public class LegalEntityForeignStateInRAFPType {

    @XmlElement(required = true)
    protected LegalEntityForeignStateDataType legalEntityForeignStateDataInfo;
    @XmlElement(required = true)
    protected LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo filialLegalEntityForeignStateInfo;

    /**
     * Gets the value of the legalEntityForeignStateDataInfo property.
     * 
     * @return
     *     possible object is
     *     {@link LegalEntityForeignStateDataType }
     *     
     */
    public LegalEntityForeignStateDataType getLegalEntityForeignStateDataInfo() {
        return legalEntityForeignStateDataInfo;
    }

    /**
     * Sets the value of the legalEntityForeignStateDataInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link LegalEntityForeignStateDataType }
     *     
     */
    public void setLegalEntityForeignStateDataInfo(LegalEntityForeignStateDataType value) {
        this.legalEntityForeignStateDataInfo = value;
    }

    /**
     * Gets the value of the filialLegalEntityForeignStateInfo property.
     * 
     * @return
     *     possible object is
     *     {@link LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo }
     *     
     */
    public LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo getFilialLegalEntityForeignStateInfo() {
        return filialLegalEntityForeignStateInfo;
    }

    /**
     * Sets the value of the filialLegalEntityForeignStateInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo }
     *     
     */
    public void setFilialLegalEntityForeignStateInfo(LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo value) {
        this.filialLegalEntityForeignStateInfo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="filialLegalEntityForeignStateDataInfo">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="fullName" type="{http://zakupki.gov.ru/eruz/base/1}text1000Type"/>
     *                   &lt;element name="shortName" type="{http://zakupki.gov.ru/eruz/base/1}text510Type" minOccurs="0"/>
     *                   &lt;element name="INN" type="{http://zakupki.gov.ru/eruz/base/1}innOrganizationType"/>
     *                   &lt;element name="KPP" type="{http://zakupki.gov.ru/eruz/base/1}kppType"/>
     *                   &lt;element name="regDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *                   &lt;element name="factAdressInfo" type="{http://zakupki.gov.ru/eruz/types/1}factAdressType"/>
     *                   &lt;element name="OKVEDs">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="OKVED" type="{http://zakupki.gov.ru/eruz/common/1}OKVEDRef" maxOccurs="unbounded"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="maxPrice" type="{http://zakupki.gov.ru/eruz/base/1}moneyMaxLengthToPoint21Type"/>
     *                   &lt;element name="timeZoneInfo" type="{http://zakupki.gov.ru/eruz/common/1}timeZoneRef"/>
     *                   &lt;element name="isParticipant" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="headInfo">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="nameInfo" type="{http://zakupki.gov.ru/eruz/common/1}personType"/>
     *                   &lt;element name="position" type="{http://zakupki.gov.ru/eruz/base/1}positionType"/>
     *                   &lt;element name="identityDocInfo" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;choice>
     *                             &lt;element name="passportRFInfo" type="{http://zakupki.gov.ru/eruz/common/1}passportRFType"/>
     *                             &lt;element name="internationalPassportRFInfo" type="{http://zakupki.gov.ru/eruz/common/1}internationalPassportRFType"/>
     *                             &lt;element name="passportForeignInfo" type="{http://zakupki.gov.ru/eruz/types/1}passportForeignType"/>
     *                             &lt;element name="sojournPermitInfo" type="{http://zakupki.gov.ru/eruz/types/1}sojournPermitType"/>
     *                             &lt;element name="permamentResidencyInfo" type="{http://zakupki.gov.ru/eruz/types/1}permamentResidencyType"/>
     *                           &lt;/choice>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="INN" type="{http://zakupki.gov.ru/eruz/base/1}innIndividualType" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="contactInfo">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://zakupki.gov.ru/eruz/common/1}contactsType">
     *                 &lt;sequence>
     *                   &lt;element name="postAdress" type="{http://zakupki.gov.ru/eruz/base/1}text2000Type"/>
     *                   &lt;element name="url" type="{http://zakupki.gov.ru/eruz/base/1}hrefType" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="attachmentsInfo">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="foundingDocLegalEntityInfo" type="{http://zakupki.gov.ru/eruz/common/1}attachmentListType"/>
     *                   &lt;element name="consentDecisionInfo" type="{http://zakupki.gov.ru/eruz/common/1}attachmentListType"/>
     *                   &lt;element name="govRegistrationLegalEntityDocInfo" type="{http://zakupki.gov.ru/eruz/common/1}attachmentListType"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "filialLegalEntityForeignStateDataInfo",
        "headInfo",
        "contactInfo",
        "attachmentsInfo"
    })
    public static class FilialLegalEntityForeignStateInfo {

        @XmlElement(required = true)
        protected LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.FilialLegalEntityForeignStateDataInfo filialLegalEntityForeignStateDataInfo;
        @XmlElement(required = true)
        protected LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.HeadInfo headInfo;
        @XmlElement(required = true)
        protected LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.ContactInfo contactInfo;
        @XmlElement(required = true)
        protected LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.AttachmentsInfo attachmentsInfo;

        /**
         * Gets the value of the filialLegalEntityForeignStateDataInfo property.
         * 
         * @return
         *     possible object is
         *     {@link LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.FilialLegalEntityForeignStateDataInfo }
         *     
         */
        public LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.FilialLegalEntityForeignStateDataInfo getFilialLegalEntityForeignStateDataInfo() {
            return filialLegalEntityForeignStateDataInfo;
        }

        /**
         * Sets the value of the filialLegalEntityForeignStateDataInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.FilialLegalEntityForeignStateDataInfo }
         *     
         */
        public void setFilialLegalEntityForeignStateDataInfo(LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.FilialLegalEntityForeignStateDataInfo value) {
            this.filialLegalEntityForeignStateDataInfo = value;
        }

        /**
         * Gets the value of the headInfo property.
         * 
         * @return
         *     possible object is
         *     {@link LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.HeadInfo }
         *     
         */
        public LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.HeadInfo getHeadInfo() {
            return headInfo;
        }

        /**
         * Sets the value of the headInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.HeadInfo }
         *     
         */
        public void setHeadInfo(LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.HeadInfo value) {
            this.headInfo = value;
        }

        /**
         * Gets the value of the contactInfo property.
         * 
         * @return
         *     possible object is
         *     {@link LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.ContactInfo }
         *     
         */
        public LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.ContactInfo getContactInfo() {
            return contactInfo;
        }

        /**
         * Sets the value of the contactInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.ContactInfo }
         *     
         */
        public void setContactInfo(LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.ContactInfo value) {
            this.contactInfo = value;
        }

        /**
         * Gets the value of the attachmentsInfo property.
         * 
         * @return
         *     possible object is
         *     {@link LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.AttachmentsInfo }
         *     
         */
        public LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.AttachmentsInfo getAttachmentsInfo() {
            return attachmentsInfo;
        }

        /**
         * Sets the value of the attachmentsInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.AttachmentsInfo }
         *     
         */
        public void setAttachmentsInfo(LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.AttachmentsInfo value) {
            this.attachmentsInfo = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="foundingDocLegalEntityInfo" type="{http://zakupki.gov.ru/eruz/common/1}attachmentListType"/>
         *         &lt;element name="consentDecisionInfo" type="{http://zakupki.gov.ru/eruz/common/1}attachmentListType"/>
         *         &lt;element name="govRegistrationLegalEntityDocInfo" type="{http://zakupki.gov.ru/eruz/common/1}attachmentListType"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "foundingDocLegalEntityInfo",
            "consentDecisionInfo",
            "govRegistrationLegalEntityDocInfo"
        })
        public static class AttachmentsInfo {

            @XmlElement(required = true)
            protected AttachmentListType foundingDocLegalEntityInfo;
            @XmlElement(required = true)
            protected AttachmentListType consentDecisionInfo;
            @XmlElement(required = true)
            protected AttachmentListType govRegistrationLegalEntityDocInfo;

            /**
             * Gets the value of the foundingDocLegalEntityInfo property.
             * 
             * @return
             *     possible object is
             *     {@link AttachmentListType }
             *     
             */
            public AttachmentListType getFoundingDocLegalEntityInfo() {
                return foundingDocLegalEntityInfo;
            }

            /**
             * Sets the value of the foundingDocLegalEntityInfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link AttachmentListType }
             *     
             */
            public void setFoundingDocLegalEntityInfo(AttachmentListType value) {
                this.foundingDocLegalEntityInfo = value;
            }

            /**
             * Gets the value of the consentDecisionInfo property.
             * 
             * @return
             *     possible object is
             *     {@link AttachmentListType }
             *     
             */
            public AttachmentListType getConsentDecisionInfo() {
                return consentDecisionInfo;
            }

            /**
             * Sets the value of the consentDecisionInfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link AttachmentListType }
             *     
             */
            public void setConsentDecisionInfo(AttachmentListType value) {
                this.consentDecisionInfo = value;
            }

            /**
             * Gets the value of the govRegistrationLegalEntityDocInfo property.
             * 
             * @return
             *     possible object is
             *     {@link AttachmentListType }
             *     
             */
            public AttachmentListType getGovRegistrationLegalEntityDocInfo() {
                return govRegistrationLegalEntityDocInfo;
            }

            /**
             * Sets the value of the govRegistrationLegalEntityDocInfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link AttachmentListType }
             *     
             */
            public void setGovRegistrationLegalEntityDocInfo(AttachmentListType value) {
                this.govRegistrationLegalEntityDocInfo = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://zakupki.gov.ru/eruz/common/1}contactsType">
         *       &lt;sequence>
         *         &lt;element name="postAdress" type="{http://zakupki.gov.ru/eruz/base/1}text2000Type"/>
         *         &lt;element name="url" type="{http://zakupki.gov.ru/eruz/base/1}hrefType" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "postAdress",
            "url"
        })
        public static class ContactInfo
            extends ContactsType
        {

            @XmlElement(required = true)
            protected String postAdress;
            protected String url;

            /**
             * Gets the value of the postAdress property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPostAdress() {
                return postAdress;
            }

            /**
             * Sets the value of the postAdress property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPostAdress(String value) {
                this.postAdress = value;
            }

            /**
             * Gets the value of the url property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUrl() {
                return url;
            }

            /**
             * Sets the value of the url property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUrl(String value) {
                this.url = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="fullName" type="{http://zakupki.gov.ru/eruz/base/1}text1000Type"/>
         *         &lt;element name="shortName" type="{http://zakupki.gov.ru/eruz/base/1}text510Type" minOccurs="0"/>
         *         &lt;element name="INN" type="{http://zakupki.gov.ru/eruz/base/1}innOrganizationType"/>
         *         &lt;element name="KPP" type="{http://zakupki.gov.ru/eruz/base/1}kppType"/>
         *         &lt;element name="regDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
         *         &lt;element name="factAdressInfo" type="{http://zakupki.gov.ru/eruz/types/1}factAdressType"/>
         *         &lt;element name="OKVEDs">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="OKVED" type="{http://zakupki.gov.ru/eruz/common/1}OKVEDRef" maxOccurs="unbounded"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="maxPrice" type="{http://zakupki.gov.ru/eruz/base/1}moneyMaxLengthToPoint21Type"/>
         *         &lt;element name="timeZoneInfo" type="{http://zakupki.gov.ru/eruz/common/1}timeZoneRef"/>
         *         &lt;element name="isParticipant" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "fullName",
            "shortName",
            "inn",
            "kpp",
            "regDate",
            "factAdressInfo",
            "okveDs",
            "maxPrice",
            "timeZoneInfo",
            "isParticipant"
        })
        public static class FilialLegalEntityForeignStateDataInfo {

            @XmlElement(required = true)
            protected String fullName;
            protected String shortName;
            @XmlElement(name = "INN", required = true)
            protected String inn;
            @XmlElement(name = "KPP", required = true)
            protected String kpp;
            @XmlElement(required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar regDate;
            @XmlElement(required = true)
            protected FactAdressType factAdressInfo;
            @XmlElement(name = "OKVEDs", required = true)
            protected LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.FilialLegalEntityForeignStateDataInfo.OKVEDs okveDs;
            @XmlElement(required = true)
            protected String maxPrice;
            @XmlElement(required = true)
            protected TimeZoneRef timeZoneInfo;
            protected boolean isParticipant;

            /**
             * Gets the value of the fullName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFullName() {
                return fullName;
            }

            /**
             * Sets the value of the fullName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFullName(String value) {
                this.fullName = value;
            }

            /**
             * Gets the value of the shortName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getShortName() {
                return shortName;
            }

            /**
             * Sets the value of the shortName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setShortName(String value) {
                this.shortName = value;
            }

            /**
             * Gets the value of the inn property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getINN() {
                return inn;
            }

            /**
             * Sets the value of the inn property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setINN(String value) {
                this.inn = value;
            }

            /**
             * Gets the value of the kpp property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getKPP() {
                return kpp;
            }

            /**
             * Sets the value of the kpp property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setKPP(String value) {
                this.kpp = value;
            }

            /**
             * Gets the value of the regDate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getRegDate() {
                return regDate;
            }

            /**
             * Sets the value of the regDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setRegDate(XMLGregorianCalendar value) {
                this.regDate = value;
            }

            /**
             * Gets the value of the factAdressInfo property.
             * 
             * @return
             *     possible object is
             *     {@link FactAdressType }
             *     
             */
            public FactAdressType getFactAdressInfo() {
                return factAdressInfo;
            }

            /**
             * Sets the value of the factAdressInfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link FactAdressType }
             *     
             */
            public void setFactAdressInfo(FactAdressType value) {
                this.factAdressInfo = value;
            }

            /**
             * Gets the value of the okveDs property.
             * 
             * @return
             *     possible object is
             *     {@link LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.FilialLegalEntityForeignStateDataInfo.OKVEDs }
             *     
             */
            public LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.FilialLegalEntityForeignStateDataInfo.OKVEDs getOKVEDs() {
                return okveDs;
            }

            /**
             * Sets the value of the okveDs property.
             * 
             * @param value
             *     allowed object is
             *     {@link LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.FilialLegalEntityForeignStateDataInfo.OKVEDs }
             *     
             */
            public void setOKVEDs(LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.FilialLegalEntityForeignStateDataInfo.OKVEDs value) {
                this.okveDs = value;
            }

            /**
             * Gets the value of the maxPrice property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMaxPrice() {
                return maxPrice;
            }

            /**
             * Sets the value of the maxPrice property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMaxPrice(String value) {
                this.maxPrice = value;
            }

            /**
             * Gets the value of the timeZoneInfo property.
             * 
             * @return
             *     possible object is
             *     {@link TimeZoneRef }
             *     
             */
            public TimeZoneRef getTimeZoneInfo() {
                return timeZoneInfo;
            }

            /**
             * Sets the value of the timeZoneInfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link TimeZoneRef }
             *     
             */
            public void setTimeZoneInfo(TimeZoneRef value) {
                this.timeZoneInfo = value;
            }

            /**
             * Gets the value of the isParticipant property.
             * 
             */
            public boolean isIsParticipant() {
                return isParticipant;
            }

            /**
             * Sets the value of the isParticipant property.
             * 
             */
            public void setIsParticipant(boolean value) {
                this.isParticipant = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="OKVED" type="{http://zakupki.gov.ru/eruz/common/1}OKVEDRef" maxOccurs="unbounded"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "okved"
            })
            public static class OKVEDs {

                @XmlElement(name = "OKVED", required = true)
                protected List<OKVEDRef> okved;

                /**
                 * Gets the value of the okved property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the okved property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getOKVED().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link OKVEDRef }
                 * 
                 * 
                 */
                public List<OKVEDRef> getOKVED() {
                    if (okved == null) {
                        okved = new ArrayList<OKVEDRef>();
                    }
                    return this.okved;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="nameInfo" type="{http://zakupki.gov.ru/eruz/common/1}personType"/>
         *         &lt;element name="position" type="{http://zakupki.gov.ru/eruz/base/1}positionType"/>
         *         &lt;element name="identityDocInfo" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;choice>
         *                   &lt;element name="passportRFInfo" type="{http://zakupki.gov.ru/eruz/common/1}passportRFType"/>
         *                   &lt;element name="internationalPassportRFInfo" type="{http://zakupki.gov.ru/eruz/common/1}internationalPassportRFType"/>
         *                   &lt;element name="passportForeignInfo" type="{http://zakupki.gov.ru/eruz/types/1}passportForeignType"/>
         *                   &lt;element name="sojournPermitInfo" type="{http://zakupki.gov.ru/eruz/types/1}sojournPermitType"/>
         *                   &lt;element name="permamentResidencyInfo" type="{http://zakupki.gov.ru/eruz/types/1}permamentResidencyType"/>
         *                 &lt;/choice>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="INN" type="{http://zakupki.gov.ru/eruz/base/1}innIndividualType" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "nameInfo",
            "position",
            "identityDocInfo",
            "inn"
        })
        public static class HeadInfo {

            @XmlElement(required = true)
            protected PersonType nameInfo;
            @XmlElement(required = true)
            protected String position;
            protected LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.HeadInfo.IdentityDocInfo identityDocInfo;
            @XmlElement(name = "INN")
            protected String inn;

            /**
             * Gets the value of the nameInfo property.
             * 
             * @return
             *     possible object is
             *     {@link PersonType }
             *     
             */
            public PersonType getNameInfo() {
                return nameInfo;
            }

            /**
             * Sets the value of the nameInfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link PersonType }
             *     
             */
            public void setNameInfo(PersonType value) {
                this.nameInfo = value;
            }

            /**
             * Gets the value of the position property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPosition() {
                return position;
            }

            /**
             * Sets the value of the position property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPosition(String value) {
                this.position = value;
            }

            /**
             * Gets the value of the identityDocInfo property.
             * 
             * @return
             *     possible object is
             *     {@link LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.HeadInfo.IdentityDocInfo }
             *     
             */
            public LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.HeadInfo.IdentityDocInfo getIdentityDocInfo() {
                return identityDocInfo;
            }

            /**
             * Sets the value of the identityDocInfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.HeadInfo.IdentityDocInfo }
             *     
             */
            public void setIdentityDocInfo(LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.HeadInfo.IdentityDocInfo value) {
                this.identityDocInfo = value;
            }

            /**
             * Gets the value of the inn property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getINN() {
                return inn;
            }

            /**
             * Sets the value of the inn property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setINN(String value) {
                this.inn = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;choice>
             *         &lt;element name="passportRFInfo" type="{http://zakupki.gov.ru/eruz/common/1}passportRFType"/>
             *         &lt;element name="internationalPassportRFInfo" type="{http://zakupki.gov.ru/eruz/common/1}internationalPassportRFType"/>
             *         &lt;element name="passportForeignInfo" type="{http://zakupki.gov.ru/eruz/types/1}passportForeignType"/>
             *         &lt;element name="sojournPermitInfo" type="{http://zakupki.gov.ru/eruz/types/1}sojournPermitType"/>
             *         &lt;element name="permamentResidencyInfo" type="{http://zakupki.gov.ru/eruz/types/1}permamentResidencyType"/>
             *       &lt;/choice>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "passportRFInfo",
                "internationalPassportRFInfo",
                "passportForeignInfo",
                "sojournPermitInfo",
                "permamentResidencyInfo"
            })
            public static class IdentityDocInfo {

                protected PassportRFType passportRFInfo;
                protected InternationalPassportRFType internationalPassportRFInfo;
                protected PassportForeignType passportForeignInfo;
                protected SojournPermitType sojournPermitInfo;
                protected PermamentResidencyType permamentResidencyInfo;

                /**
                 * Gets the value of the passportRFInfo property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link PassportRFType }
                 *     
                 */
                public PassportRFType getPassportRFInfo() {
                    return passportRFInfo;
                }

                /**
                 * Sets the value of the passportRFInfo property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link PassportRFType }
                 *     
                 */
                public void setPassportRFInfo(PassportRFType value) {
                    this.passportRFInfo = value;
                }

                /**
                 * Gets the value of the internationalPassportRFInfo property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link InternationalPassportRFType }
                 *     
                 */
                public InternationalPassportRFType getInternationalPassportRFInfo() {
                    return internationalPassportRFInfo;
                }

                /**
                 * Sets the value of the internationalPassportRFInfo property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link InternationalPassportRFType }
                 *     
                 */
                public void setInternationalPassportRFInfo(InternationalPassportRFType value) {
                    this.internationalPassportRFInfo = value;
                }

                /**
                 * Gets the value of the passportForeignInfo property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link PassportForeignType }
                 *     
                 */
                public PassportForeignType getPassportForeignInfo() {
                    return passportForeignInfo;
                }

                /**
                 * Sets the value of the passportForeignInfo property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link PassportForeignType }
                 *     
                 */
                public void setPassportForeignInfo(PassportForeignType value) {
                    this.passportForeignInfo = value;
                }

                /**
                 * Gets the value of the sojournPermitInfo property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link SojournPermitType }
                 *     
                 */
                public SojournPermitType getSojournPermitInfo() {
                    return sojournPermitInfo;
                }

                /**
                 * Sets the value of the sojournPermitInfo property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link SojournPermitType }
                 *     
                 */
                public void setSojournPermitInfo(SojournPermitType value) {
                    this.sojournPermitInfo = value;
                }

                /**
                 * Gets the value of the permamentResidencyInfo property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link PermamentResidencyType }
                 *     
                 */
                public PermamentResidencyType getPermamentResidencyInfo() {
                    return permamentResidencyInfo;
                }

                /**
                 * Sets the value of the permamentResidencyInfo property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link PermamentResidencyType }
                 *     
                 */
                public void setPermamentResidencyInfo(PermamentResidencyType value) {
                    this.permamentResidencyInfo = value;
                }

            }

        }

    }

}
