//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.02 at 04:13:19 PM MSK 
//


package ru.gov.zakupki.eruz.types._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import ru.gov.zakupki.eruz.common._1.AttachmentType;


/**
 * Тип: Управляющая организация
 * 
 * <p>Java class for managingOrganizationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="managingOrganizationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fullName" type="{http://zakupki.gov.ru/eruz/base/1}text1000Type"/>
 *         &lt;element name="INN" type="{http://zakupki.gov.ru/eruz/base/1}innOrganizationType"/>
 *         &lt;element name="KPP" type="{http://zakupki.gov.ru/eruz/base/1}kppType"/>
 *         &lt;element name="OGRN" type="{http://zakupki.gov.ru/eruz/base/1}OGRNCodeType"/>
 *         &lt;element name="EGRULStatementInfo" type="{http://zakupki.gov.ru/eruz/common/1}attachmentType" minOccurs="0"/>
 *         &lt;element name="managingOrganization" type="{http://zakupki.gov.ru/eruz/types/1}managingOrganizationType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "managingOrganizationType", propOrder = {
    "fullName",
    "inn",
    "kpp",
    "ogrn",
    "egrulStatementInfo",
    "managingOrganization"
})
public class ManagingOrganizationType {

    @XmlElement(required = true)
    protected String fullName;
    @XmlElement(name = "INN", required = true)
    protected String inn;
    @XmlElement(name = "KPP", required = true)
    protected String kpp;
    @XmlElement(name = "OGRN", required = true)
    protected String ogrn;
    @XmlElement(name = "EGRULStatementInfo")
    protected AttachmentType egrulStatementInfo;
    protected ManagingOrganizationType managingOrganization;

    /**
     * Gets the value of the fullName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * Sets the value of the fullName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullName(String value) {
        this.fullName = value;
    }

    /**
     * Gets the value of the inn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINN() {
        return inn;
    }

    /**
     * Sets the value of the inn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINN(String value) {
        this.inn = value;
    }

    /**
     * Gets the value of the kpp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKPP() {
        return kpp;
    }

    /**
     * Sets the value of the kpp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKPP(String value) {
        this.kpp = value;
    }

    /**
     * Gets the value of the ogrn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOGRN() {
        return ogrn;
    }

    /**
     * Sets the value of the ogrn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOGRN(String value) {
        this.ogrn = value;
    }

    /**
     * Gets the value of the egrulStatementInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AttachmentType }
     *     
     */
    public AttachmentType getEGRULStatementInfo() {
        return egrulStatementInfo;
    }

    /**
     * Sets the value of the egrulStatementInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttachmentType }
     *     
     */
    public void setEGRULStatementInfo(AttachmentType value) {
        this.egrulStatementInfo = value;
    }

    /**
     * Gets the value of the managingOrganization property.
     * 
     * @return
     *     possible object is
     *     {@link ManagingOrganizationType }
     *     
     */
    public ManagingOrganizationType getManagingOrganization() {
        return managingOrganization;
    }

    /**
     * Sets the value of the managingOrganization property.
     * 
     * @param value
     *     allowed object is
     *     {@link ManagingOrganizationType }
     *     
     */
    public void setManagingOrganization(ManagingOrganizationType value) {
        this.managingOrganization = value;
    }

}
