//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.02 at 04:14:17 PM MSK 
//


package ru.gov.zakupki.eruz.types._1;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.gov.zakupki.eruz.types._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.gov.zakupki.eruz.types._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LegalEntityRFType }
     * 
     */
    public LegalEntityRFType createLegalEntityRFType() {
        return new LegalEntityRFType();
    }

    /**
     * Create an instance of {@link LegalEntityRFType.InformationPersons }
     * 
     */
    public LegalEntityRFType.InformationPersons createLegalEntityRFTypeInformationPersons() {
        return new LegalEntityRFType.InformationPersons();
    }

    /**
     * Create an instance of {@link InformationPersonType }
     * 
     */
    public InformationPersonType createInformationPersonType() {
        return new InformationPersonType();
    }

    /**
     * Create an instance of {@link LegalEntityRFDataType }
     * 
     */
    public LegalEntityRFDataType createLegalEntityRFDataType() {
        return new LegalEntityRFDataType();
    }

    /**
     * Create an instance of {@link LegalEntityForeignStateInRAFPType }
     * 
     */
    public LegalEntityForeignStateInRAFPType createLegalEntityForeignStateInRAFPType() {
        return new LegalEntityForeignStateInRAFPType();
    }

    /**
     * Create an instance of {@link LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo }
     * 
     */
    public LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo createLegalEntityForeignStateInRAFPTypeFilialLegalEntityForeignStateInfo() {
        return new LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo();
    }

    /**
     * Create an instance of {@link LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.HeadInfo }
     * 
     */
    public LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.HeadInfo createLegalEntityForeignStateInRAFPTypeFilialLegalEntityForeignStateInfoHeadInfo() {
        return new LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.HeadInfo();
    }

    /**
     * Create an instance of {@link LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.FilialLegalEntityForeignStateDataInfo }
     * 
     */
    public LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.FilialLegalEntityForeignStateDataInfo createLegalEntityForeignStateInRAFPTypeFilialLegalEntityForeignStateInfoFilialLegalEntityForeignStateDataInfo() {
        return new LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.FilialLegalEntityForeignStateDataInfo();
    }

    /**
     * Create an instance of {@link LegalEntityForeignStateNotInRAFPType }
     * 
     */
    public LegalEntityForeignStateNotInRAFPType createLegalEntityForeignStateNotInRAFPType() {
        return new LegalEntityForeignStateNotInRAFPType();
    }

    /**
     * Create an instance of {@link LegalEntityForeignStateNotInRAFPType.InformationPersons }
     * 
     */
    public LegalEntityForeignStateNotInRAFPType.InformationPersons createLegalEntityForeignStateNotInRAFPTypeInformationPersons() {
        return new LegalEntityForeignStateNotInRAFPType.InformationPersons();
    }

    /**
     * Create an instance of {@link FactAdressType }
     * 
     */
    public FactAdressType createFactAdressType() {
        return new FactAdressType();
    }

    /**
     * Create an instance of {@link AccreditationResultType }
     * 
     */
    public AccreditationResultType createAccreditationResultType() {
        return new AccreditationResultType();
    }

    /**
     * Create an instance of {@link AccreditationResultType.AccreditationInfo }
     * 
     */
    public AccreditationResultType.AccreditationInfo createAccreditationResultTypeAccreditationInfo() {
        return new AccreditationResultType.AccreditationInfo();
    }

    /**
     * Create an instance of {@link IndividualPersonForeignStateType }
     * 
     */
    public IndividualPersonForeignStateType createIndividualPersonForeignStateType() {
        return new IndividualPersonForeignStateType();
    }

    /**
     * Create an instance of {@link IndividualPersonForeignStateType.IndividualPersonForeignStateDataInfo }
     * 
     */
    public IndividualPersonForeignStateType.IndividualPersonForeignStateDataInfo createIndividualPersonForeignStateTypeIndividualPersonForeignStateDataInfo() {
        return new IndividualPersonForeignStateType.IndividualPersonForeignStateDataInfo();
    }

    /**
     * Create an instance of {@link IndividualPersonRFType }
     * 
     */
    public IndividualPersonRFType createIndividualPersonRFType() {
        return new IndividualPersonRFType();
    }

    /**
     * Create an instance of {@link IndividualPersonRFType.IndividualPersonRFDataInfo }
     * 
     */
    public IndividualPersonRFType.IndividualPersonRFDataInfo createIndividualPersonRFTypeIndividualPersonRFDataInfo() {
        return new IndividualPersonRFType.IndividualPersonRFDataInfo();
    }

    /**
     * Create an instance of {@link FilialLegalEntityRFType }
     * 
     */
    public FilialLegalEntityRFType createFilialLegalEntityRFType() {
        return new FilialLegalEntityRFType();
    }

    /**
     * Create an instance of {@link FilialLegalEntityRFType.FilialInfo }
     * 
     */
    public FilialLegalEntityRFType.FilialInfo createFilialLegalEntityRFTypeFilialInfo() {
        return new FilialLegalEntityRFType.FilialInfo();
    }

    /**
     * Create an instance of {@link FilialLegalEntityRFType.LegalEntityInfo }
     * 
     */
    public FilialLegalEntityRFType.LegalEntityInfo createFilialLegalEntityRFTypeLegalEntityInfo() {
        return new FilialLegalEntityRFType.LegalEntityInfo();
    }

    /**
     * Create an instance of {@link FilialLegalEntityRFType.LegalEntityInfo.InformationPersons }
     * 
     */
    public FilialLegalEntityRFType.LegalEntityInfo.InformationPersons createFilialLegalEntityRFTypeLegalEntityInfoInformationPersons() {
        return new FilialLegalEntityRFType.LegalEntityInfo.InformationPersons();
    }

    /**
     * Create an instance of {@link FilialLegalEntityRFType.LegalEntityInfo.InformationPersons.InformationPersonInfo }
     * 
     */
    public FilialLegalEntityRFType.LegalEntityInfo.InformationPersons.InformationPersonInfo createFilialLegalEntityRFTypeLegalEntityInfoInformationPersonsInformationPersonInfo() {
        return new FilialLegalEntityRFType.LegalEntityInfo.InformationPersons.InformationPersonInfo();
    }

    /**
     * Create an instance of {@link FilialLegalEntityRFType.LegalEntityInfo.LegalEntityRFDataInfo }
     * 
     */
    public FilialLegalEntityRFType.LegalEntityInfo.LegalEntityRFDataInfo createFilialLegalEntityRFTypeLegalEntityInfoLegalEntityRFDataInfo() {
        return new FilialLegalEntityRFType.LegalEntityInfo.LegalEntityRFDataInfo();
    }

    /**
     * Create an instance of {@link ConfirmationType }
     * 
     */
    public ConfirmationType createConfirmationType() {
        return new ConfirmationType();
    }

    /**
     * Create an instance of {@link ContractorExcludeType }
     * 
     */
    public ContractorExcludeType createContractorExcludeType() {
        return new ContractorExcludeType();
    }

    /**
     * Create an instance of {@link ContractorType }
     * 
     */
    public ContractorType createContractorType() {
        return new ContractorType();
    }

    /**
     * Create an instance of {@link IPInfoType }
     * 
     */
    public IPInfoType createIPInfoType() {
        return new IPInfoType();
    }

    /**
     * Create an instance of {@link ManagingOrganizationType }
     * 
     */
    public ManagingOrganizationType createManagingOrganizationType() {
        return new ManagingOrganizationType();
    }

    /**
     * Create an instance of {@link SojournPermitType }
     * 
     */
    public SojournPermitType createSojournPermitType() {
        return new SojournPermitType();
    }

    /**
     * Create an instance of {@link PermamentResidencyType }
     * 
     */
    public PermamentResidencyType createPermamentResidencyType() {
        return new PermamentResidencyType();
    }

    /**
     * Create an instance of {@link LegalEntityForeignStateDataType }
     * 
     */
    public LegalEntityForeignStateDataType createLegalEntityForeignStateDataType() {
        return new LegalEntityForeignStateDataType();
    }

    /**
     * Create an instance of {@link ViolationType }
     * 
     */
    public ViolationType createViolationType() {
        return new ViolationType();
    }

    /**
     * Create an instance of {@link PassportForeignType }
     * 
     */
    public PassportForeignType createPassportForeignType() {
        return new PassportForeignType();
    }

    /**
     * Create an instance of {@link LegalEntityRFType.LegalEntityRFDataInfo }
     * 
     */
    public LegalEntityRFType.LegalEntityRFDataInfo createLegalEntityRFTypeLegalEntityRFDataInfo() {
        return new LegalEntityRFType.LegalEntityRFDataInfo();
    }

    /**
     * Create an instance of {@link LegalEntityRFType.ContactInfo }
     * 
     */
    public LegalEntityRFType.ContactInfo createLegalEntityRFTypeContactInfo() {
        return new LegalEntityRFType.ContactInfo();
    }

    /**
     * Create an instance of {@link LegalEntityRFType.AttachmentsInfo }
     * 
     */
    public LegalEntityRFType.AttachmentsInfo createLegalEntityRFTypeAttachmentsInfo() {
        return new LegalEntityRFType.AttachmentsInfo();
    }

    /**
     * Create an instance of {@link LegalEntityRFType.InformationPersons.InformationPersonInfo }
     * 
     */
    public LegalEntityRFType.InformationPersons.InformationPersonInfo createLegalEntityRFTypeInformationPersonsInformationPersonInfo() {
        return new LegalEntityRFType.InformationPersons.InformationPersonInfo();
    }

    /**
     * Create an instance of {@link InformationPersonType.IdentityDocInfo }
     * 
     */
    public InformationPersonType.IdentityDocInfo createInformationPersonTypeIdentityDocInfo() {
        return new InformationPersonType.IdentityDocInfo();
    }

    /**
     * Create an instance of {@link LegalEntityRFDataType.OKVEDs }
     * 
     */
    public LegalEntityRFDataType.OKVEDs createLegalEntityRFDataTypeOKVEDs() {
        return new LegalEntityRFDataType.OKVEDs();
    }

    /**
     * Create an instance of {@link LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.ContactInfo }
     * 
     */
    public LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.ContactInfo createLegalEntityForeignStateInRAFPTypeFilialLegalEntityForeignStateInfoContactInfo() {
        return new LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.ContactInfo();
    }

    /**
     * Create an instance of {@link LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.AttachmentsInfo }
     * 
     */
    public LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.AttachmentsInfo createLegalEntityForeignStateInRAFPTypeFilialLegalEntityForeignStateInfoAttachmentsInfo() {
        return new LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.AttachmentsInfo();
    }

    /**
     * Create an instance of {@link LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.HeadInfo.IdentityDocInfo }
     * 
     */
    public LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.HeadInfo.IdentityDocInfo createLegalEntityForeignStateInRAFPTypeFilialLegalEntityForeignStateInfoHeadInfoIdentityDocInfo() {
        return new LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.HeadInfo.IdentityDocInfo();
    }

    /**
     * Create an instance of {@link LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.FilialLegalEntityForeignStateDataInfo.OKVEDs }
     * 
     */
    public LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.FilialLegalEntityForeignStateDataInfo.OKVEDs createLegalEntityForeignStateInRAFPTypeFilialLegalEntityForeignStateInfoFilialLegalEntityForeignStateDataInfoOKVEDs() {
        return new LegalEntityForeignStateInRAFPType.FilialLegalEntityForeignStateInfo.FilialLegalEntityForeignStateDataInfo.OKVEDs();
    }

    /**
     * Create an instance of {@link LegalEntityForeignStateNotInRAFPType.LegalEntityForeignStateDataInfo }
     * 
     */
    public LegalEntityForeignStateNotInRAFPType.LegalEntityForeignStateDataInfo createLegalEntityForeignStateNotInRAFPTypeLegalEntityForeignStateDataInfo() {
        return new LegalEntityForeignStateNotInRAFPType.LegalEntityForeignStateDataInfo();
    }

    /**
     * Create an instance of {@link LegalEntityForeignStateNotInRAFPType.ContactInfo }
     * 
     */
    public LegalEntityForeignStateNotInRAFPType.ContactInfo createLegalEntityForeignStateNotInRAFPTypeContactInfo() {
        return new LegalEntityForeignStateNotInRAFPType.ContactInfo();
    }

    /**
     * Create an instance of {@link LegalEntityForeignStateNotInRAFPType.AttachmentsInfo }
     * 
     */
    public LegalEntityForeignStateNotInRAFPType.AttachmentsInfo createLegalEntityForeignStateNotInRAFPTypeAttachmentsInfo() {
        return new LegalEntityForeignStateNotInRAFPType.AttachmentsInfo();
    }

    /**
     * Create an instance of {@link LegalEntityForeignStateNotInRAFPType.InformationPersons.InformationPersonInfo }
     * 
     */
    public LegalEntityForeignStateNotInRAFPType.InformationPersons.InformationPersonInfo createLegalEntityForeignStateNotInRAFPTypeInformationPersonsInformationPersonInfo() {
        return new LegalEntityForeignStateNotInRAFPType.InformationPersons.InformationPersonInfo();
    }

    /**
     * Create an instance of {@link FactAdressType.RegionInfo }
     * 
     */
    public FactAdressType.RegionInfo createFactAdressTypeRegionInfo() {
        return new FactAdressType.RegionInfo();
    }

    /**
     * Create an instance of {@link FactAdressType.AreaInfo }
     * 
     */
    public FactAdressType.AreaInfo createFactAdressTypeAreaInfo() {
        return new FactAdressType.AreaInfo();
    }

    /**
     * Create an instance of {@link FactAdressType.CityInfo }
     * 
     */
    public FactAdressType.CityInfo createFactAdressTypeCityInfo() {
        return new FactAdressType.CityInfo();
    }

    /**
     * Create an instance of {@link FactAdressType.SettlementInfo }
     * 
     */
    public FactAdressType.SettlementInfo createFactAdressTypeSettlementInfo() {
        return new FactAdressType.SettlementInfo();
    }

    /**
     * Create an instance of {@link FactAdressType.ShortStreetInfo }
     * 
     */
    public FactAdressType.ShortStreetInfo createFactAdressTypeShortStreetInfo() {
        return new FactAdressType.ShortStreetInfo();
    }

    /**
     * Create an instance of {@link AccreditationResultType.AccreditationInfo.Violations }
     * 
     */
    public AccreditationResultType.AccreditationInfo.Violations createAccreditationResultTypeAccreditationInfoViolations() {
        return new AccreditationResultType.AccreditationInfo.Violations();
    }

    /**
     * Create an instance of {@link IndividualPersonForeignStateType.ContactInfo }
     * 
     */
    public IndividualPersonForeignStateType.ContactInfo createIndividualPersonForeignStateTypeContactInfo() {
        return new IndividualPersonForeignStateType.ContactInfo();
    }

    /**
     * Create an instance of {@link IndividualPersonForeignStateType.AttachmentsInfo }
     * 
     */
    public IndividualPersonForeignStateType.AttachmentsInfo createIndividualPersonForeignStateTypeAttachmentsInfo() {
        return new IndividualPersonForeignStateType.AttachmentsInfo();
    }

    /**
     * Create an instance of {@link IndividualPersonForeignStateType.IndividualPersonForeignStateDataInfo.IdentityDocInfo }
     * 
     */
    public IndividualPersonForeignStateType.IndividualPersonForeignStateDataInfo.IdentityDocInfo createIndividualPersonForeignStateTypeIndividualPersonForeignStateDataInfoIdentityDocInfo() {
        return new IndividualPersonForeignStateType.IndividualPersonForeignStateDataInfo.IdentityDocInfo();
    }

    /**
     * Create an instance of {@link IndividualPersonForeignStateType.IndividualPersonForeignStateDataInfo.IPInfo }
     * 
     */
    public IndividualPersonForeignStateType.IndividualPersonForeignStateDataInfo.IPInfo createIndividualPersonForeignStateTypeIndividualPersonForeignStateDataInfoIPInfo() {
        return new IndividualPersonForeignStateType.IndividualPersonForeignStateDataInfo.IPInfo();
    }

    /**
     * Create an instance of {@link IndividualPersonRFType.ContactInfo }
     * 
     */
    public IndividualPersonRFType.ContactInfo createIndividualPersonRFTypeContactInfo() {
        return new IndividualPersonRFType.ContactInfo();
    }

    /**
     * Create an instance of {@link IndividualPersonRFType.AttachmentsInfo }
     * 
     */
    public IndividualPersonRFType.AttachmentsInfo createIndividualPersonRFTypeAttachmentsInfo() {
        return new IndividualPersonRFType.AttachmentsInfo();
    }

    /**
     * Create an instance of {@link IndividualPersonRFType.IndividualPersonRFDataInfo.IdentityDocInfo }
     * 
     */
    public IndividualPersonRFType.IndividualPersonRFDataInfo.IdentityDocInfo createIndividualPersonRFTypeIndividualPersonRFDataInfoIdentityDocInfo() {
        return new IndividualPersonRFType.IndividualPersonRFDataInfo.IdentityDocInfo();
    }

    /**
     * Create an instance of {@link IndividualPersonRFType.IndividualPersonRFDataInfo.IPInfo }
     * 
     */
    public IndividualPersonRFType.IndividualPersonRFDataInfo.IPInfo createIndividualPersonRFTypeIndividualPersonRFDataInfoIPInfo() {
        return new IndividualPersonRFType.IndividualPersonRFDataInfo.IPInfo();
    }

    /**
     * Create an instance of {@link FilialLegalEntityRFType.FilialInfo.FilialLegalEntityRFDataInfo }
     * 
     */
    public FilialLegalEntityRFType.FilialInfo.FilialLegalEntityRFDataInfo createFilialLegalEntityRFTypeFilialInfoFilialLegalEntityRFDataInfo() {
        return new FilialLegalEntityRFType.FilialInfo.FilialLegalEntityRFDataInfo();
    }

    /**
     * Create an instance of {@link FilialLegalEntityRFType.FilialInfo.FilialContactInfo }
     * 
     */
    public FilialLegalEntityRFType.FilialInfo.FilialContactInfo createFilialLegalEntityRFTypeFilialInfoFilialContactInfo() {
        return new FilialLegalEntityRFType.FilialInfo.FilialContactInfo();
    }

    /**
     * Create an instance of {@link FilialLegalEntityRFType.FilialInfo.AttachmentsInfo }
     * 
     */
    public FilialLegalEntityRFType.FilialInfo.AttachmentsInfo createFilialLegalEntityRFTypeFilialInfoAttachmentsInfo() {
        return new FilialLegalEntityRFType.FilialInfo.AttachmentsInfo();
    }

    /**
     * Create an instance of {@link FilialLegalEntityRFType.LegalEntityInfo.InformationPersons.InformationPersonInfo.IdentityDocInfo }
     * 
     */
    public FilialLegalEntityRFType.LegalEntityInfo.InformationPersons.InformationPersonInfo.IdentityDocInfo createFilialLegalEntityRFTypeLegalEntityInfoInformationPersonsInformationPersonInfoIdentityDocInfo() {
        return new FilialLegalEntityRFType.LegalEntityInfo.InformationPersons.InformationPersonInfo.IdentityDocInfo();
    }

    /**
     * Create an instance of {@link FilialLegalEntityRFType.LegalEntityInfo.LegalEntityRFDataInfo.RegistryNum }
     * 
     */
    public FilialLegalEntityRFType.LegalEntityInfo.LegalEntityRFDataInfo.RegistryNum createFilialLegalEntityRFTypeLegalEntityInfoLegalEntityRFDataInfoRegistryNum() {
        return new FilialLegalEntityRFType.LegalEntityInfo.LegalEntityRFDataInfo.RegistryNum();
    }

    /**
     * Create an instance of {@link ConfirmationType.Violations }
     * 
     */
    public ConfirmationType.Violations createConfirmationTypeViolations() {
        return new ConfirmationType.Violations();
    }

    /**
     * Create an instance of {@link ConfirmationType.MissingIndexNums }
     * 
     */
    public ConfirmationType.MissingIndexNums createConfirmationTypeMissingIndexNums() {
        return new ConfirmationType.MissingIndexNums();
    }

    /**
     * Create an instance of {@link ContractorExcludeType.CommonInfo }
     * 
     */
    public ContractorExcludeType.CommonInfo createContractorExcludeTypeCommonInfo() {
        return new ContractorExcludeType.CommonInfo();
    }

    /**
     * Create an instance of {@link ContractorExcludeType.AttachmentsInfo }
     * 
     */
    public ContractorExcludeType.AttachmentsInfo createContractorExcludeTypeAttachmentsInfo() {
        return new ContractorExcludeType.AttachmentsInfo();
    }

    /**
     * Create an instance of {@link ContractorExcludeType.PrintFormFieldsInfo }
     * 
     */
    public ContractorExcludeType.PrintFormFieldsInfo createContractorExcludeTypePrintFormFieldsInfo() {
        return new ContractorExcludeType.PrintFormFieldsInfo();
    }

    /**
     * Create an instance of {@link ContractorType.CommonInfo }
     * 
     */
    public ContractorType.CommonInfo createContractorTypeCommonInfo() {
        return new ContractorType.CommonInfo();
    }

    /**
     * Create an instance of {@link ContractorType.ContractorInfo }
     * 
     */
    public ContractorType.ContractorInfo createContractorTypeContractorInfo() {
        return new ContractorType.ContractorInfo();
    }

}
