//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.02 at 04:13:19 PM MSK 
//


package ru.gov.zakupki.eruz.types._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Тип: Нарушение приема
 * 
 * <p>Java class for violationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="violationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="errCode" type="{http://zakupki.gov.ru/eruz/base/1}text10Type"/>
 *         &lt;element name="level" type="{http://zakupki.gov.ru/eruz/types/1}violationLevelType"/>
 *         &lt;element name="name" type="{http://zakupki.gov.ru/eruz/base/1}text200Type"/>
 *         &lt;element name="description" type="{http://zakupki.gov.ru/eruz/base/1}text2000Type" minOccurs="0"/>
 *         &lt;element name="fullErrorLog" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "violationType", propOrder = {
    "errCode",
    "level",
    "name",
    "description",
    "fullErrorLog"
})
public class ViolationType {

    @XmlElement(required = true)
    protected String errCode;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected ViolationLevelType level;
    @XmlElement(required = true)
    protected String name;
    protected String description;
    protected byte[] fullErrorLog;

    /**
     * Gets the value of the errCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrCode() {
        return errCode;
    }

    /**
     * Sets the value of the errCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrCode(String value) {
        this.errCode = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link ViolationLevelType }
     *     
     */
    public ViolationLevelType getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link ViolationLevelType }
     *     
     */
    public void setLevel(ViolationLevelType value) {
        this.level = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the fullErrorLog property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getFullErrorLog() {
        return fullErrorLog;
    }

    /**
     * Sets the value of the fullErrorLog property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setFullErrorLog(byte[] value) {
        this.fullErrorLog = value;
    }

}
