//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.02 at 04:13:19 PM MSK 
//


package ru.gov.zakupki.eruz.integration._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;
import ru.gov.zakupki.eruz.base._1.IndexModeType;
import ru.gov.zakupki.eruz.base._1.IndexObjectTypeEnum;
import ru.gov.zakupki.eruz.base._1.SignatureType;


/**
 * Пакет данных AS2 протокола
 * 
 * <p>Java class for as2PacketType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="as2PacketType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="index">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="id" type="{http://zakupki.gov.ru/eruz/base/1}guidType"/>
 *                   &lt;element name="sender" type="{http://zakupki.gov.ru/eruz/base/1}text200Type"/>
 *                   &lt;element name="receiver" type="{http://zakupki.gov.ru/eruz/base/1}text200Type"/>
 *                   &lt;element name="createDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="objectType" type="{http://zakupki.gov.ru/eruz/base/1}indexObjectTypeEnum"/>
 *                   &lt;element name="objectId" type="{http://zakupki.gov.ru/eruz/base/1}guidType" minOccurs="0"/>
 *                   &lt;element name="indexNum" type="{http://zakupki.gov.ru/eruz/base/1}indexNumType" minOccurs="0"/>
 *                   &lt;element name="signature">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>base64Binary">
 *                           &lt;attribute name="type" use="required" type="{http://zakupki.gov.ru/eruz/base/1}signatureType" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="mode" type="{http://zakupki.gov.ru/eruz/base/1}indexModeType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "as2PacketType", propOrder = {
    "index"
})
@XmlSeeAlso({
    EruzConfirmation.class,
    EruzContractor.class,
    EruzMasterData.class,
    EruzAccreditationResult.class,
    EruzContractorExclude.class
})
public abstract class As2PacketType {

    @XmlElement(required = true)
    protected As2PacketType.Index index;

    /**
     * Gets the value of the index property.
     * 
     * @return
     *     possible object is
     *     {@link As2PacketType.Index }
     *     
     */
    public As2PacketType.Index getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     * 
     * @param value
     *     allowed object is
     *     {@link As2PacketType.Index }
     *     
     */
    public void setIndex(As2PacketType.Index value) {
        this.index = value;
    }


    /**
     * Индексная карточка пакета данных
     * 
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="id" type="{http://zakupki.gov.ru/eruz/base/1}guidType"/>
     *         &lt;element name="sender" type="{http://zakupki.gov.ru/eruz/base/1}text200Type"/>
     *         &lt;element name="receiver" type="{http://zakupki.gov.ru/eruz/base/1}text200Type"/>
     *         &lt;element name="createDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="objectType" type="{http://zakupki.gov.ru/eruz/base/1}indexObjectTypeEnum"/>
     *         &lt;element name="objectId" type="{http://zakupki.gov.ru/eruz/base/1}guidType" minOccurs="0"/>
     *         &lt;element name="indexNum" type="{http://zakupki.gov.ru/eruz/base/1}indexNumType" minOccurs="0"/>
     *         &lt;element name="signature">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>base64Binary">
     *                 &lt;attribute name="type" use="required" type="{http://zakupki.gov.ru/eruz/base/1}signatureType" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="mode" type="{http://zakupki.gov.ru/eruz/base/1}indexModeType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "sender",
        "receiver",
        "createDateTime",
        "objectType",
        "objectId",
        "indexNum",
        "signature",
        "mode"
    })
    public static class Index {

        @XmlElement(required = true)
        protected String id;
        @XmlElement(required = true)
        protected String sender;
        @XmlElement(required = true)
        protected String receiver;
        @XmlElement(required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar createDateTime;
        @XmlElement(required = true)
        @XmlSchemaType(name = "string")
        protected IndexObjectTypeEnum objectType;
        protected String objectId;
        protected Integer indexNum;
        @XmlElement(required = true)
        protected As2PacketType.Index.Signature signature;
        @XmlElement(required = true)
        @XmlSchemaType(name = "string")
        protected IndexModeType mode;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the sender property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSender() {
            return sender;
        }

        /**
         * Sets the value of the sender property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSender(String value) {
            this.sender = value;
        }

        /**
         * Gets the value of the receiver property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReceiver() {
            return receiver;
        }

        /**
         * Sets the value of the receiver property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReceiver(String value) {
            this.receiver = value;
        }

        /**
         * Gets the value of the createDateTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getCreateDateTime() {
            return createDateTime;
        }

        /**
         * Sets the value of the createDateTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setCreateDateTime(XMLGregorianCalendar value) {
            this.createDateTime = value;
        }

        /**
         * Gets the value of the objectType property.
         * 
         * @return
         *     possible object is
         *     {@link IndexObjectTypeEnum }
         *     
         */
        public IndexObjectTypeEnum getObjectType() {
            return objectType;
        }

        /**
         * Sets the value of the objectType property.
         * 
         * @param value
         *     allowed object is
         *     {@link IndexObjectTypeEnum }
         *     
         */
        public void setObjectType(IndexObjectTypeEnum value) {
            this.objectType = value;
        }

        /**
         * Gets the value of the objectId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getObjectId() {
            return objectId;
        }

        /**
         * Sets the value of the objectId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setObjectId(String value) {
            this.objectId = value;
        }

        /**
         * Gets the value of the indexNum property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getIndexNum() {
            return indexNum;
        }

        /**
         * Sets the value of the indexNum property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setIndexNum(Integer value) {
            this.indexNum = value;
        }

        /**
         * Gets the value of the signature property.
         * 
         * @return
         *     possible object is
         *     {@link As2PacketType.Index.Signature }
         *     
         */
        public As2PacketType.Index.Signature getSignature() {
            return signature;
        }

        /**
         * Sets the value of the signature property.
         * 
         * @param value
         *     allowed object is
         *     {@link As2PacketType.Index.Signature }
         *     
         */
        public void setSignature(As2PacketType.Index.Signature value) {
            this.signature = value;
        }

        /**
         * Gets the value of the mode property.
         * 
         * @return
         *     possible object is
         *     {@link IndexModeType }
         *     
         */
        public IndexModeType getMode() {
            return mode;
        }

        /**
         * Sets the value of the mode property.
         * 
         * @param value
         *     allowed object is
         *     {@link IndexModeType }
         *     
         */
        public void setMode(IndexModeType value) {
            this.mode = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>base64Binary">
         *       &lt;attribute name="type" use="required" type="{http://zakupki.gov.ru/eruz/base/1}signatureType" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Signature {

            @XmlValue
            protected byte[] value;
            @XmlAttribute(name = "type", required = true)
            protected SignatureType type;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     byte[]
             */
            public byte[] getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     byte[]
             */
            public void setValue(byte[] value) {
                this.value = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link SignatureType }
             *     
             */
            public SignatureType getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link SignatureType }
             *     
             */
            public void setType(SignatureType value) {
                this.type = value;
            }

        }

    }

}
