//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.02 at 03:51:32 PM MSK 
//


package ru.gov.zakupki.eruz.integration._1;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.gov.zakupki.eruz.integration._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.gov.zakupki.eruz.integration._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ru.gov.zakupki.eruz.integration._1.As2PacketType.Index }
     * 
     */
    public ru.gov.zakupki.eruz.integration._1.As2PacketType.Index createAs2PacketTypeIndex() {
        return new ru.gov.zakupki.eruz.integration._1.As2PacketType.Index();
    }

    /**
     * Create an instance of {@link EruzContractorExclude }
     * 
     */
    public EruzContractorExclude createEruzContractorExclude() {
        return new EruzContractorExclude();
    }

    /**
     * Create an instance of {@link EruzAccreditationResult }
     * 
     */
    public EruzAccreditationResult createEruzAccreditationResult() {
        return new EruzAccreditationResult();
    }

    /**
     * Create an instance of {@link EruzMasterData }
     * 
     */
    public EruzMasterData createEruzMasterData() {
        return new EruzMasterData();
    }

    /**
     * Create an instance of {@link EruzContractor }
     * 
     */
    public EruzContractor createEruzContractor() {
        return new EruzContractor();
    }

    /**
     * Create an instance of {@link EruzConfirmation }
     * 
     */
    public EruzConfirmation createEruzConfirmation() {
        return new EruzConfirmation();
    }

    /**
     * Create an instance of {@link ru.gov.zakupki.eruz.integration._1.As2PacketType.Index.Signature }
     * 
     */
    public ru.gov.zakupki.eruz.integration._1.As2PacketType.Index.Signature createAs2PacketTypeIndexSignature() {
        return new ru.gov.zakupki.eruz.integration._1.As2PacketType.Index.Signature();
    }

}
