//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.02 at 04:13:19 PM MSK 
//


package ru.gov.zakupki.oos.printform._1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import ru.gov.zakupki.eruz.types._1.ContractorExcludeType;
import ru.gov.zakupki.eruz.types._1.ContractorType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.gov.zakupki.oos.printform._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EruzContractorExclude_QNAME = new QName("http://zakupki.gov.ru/oos/printform/1", "eruzContractorExclude");
    private final static QName _EruzContractor_QNAME = new QName("http://zakupki.gov.ru/oos/printform/1", "eruzContractor");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.gov.zakupki.oos.printform._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContractorExcludeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://zakupki.gov.ru/oos/printform/1", name = "eruzContractorExclude")
    public JAXBElement<ContractorExcludeType> createEruzContractorExclude(ContractorExcludeType value) {
        return new JAXBElement<ContractorExcludeType>(_EruzContractorExclude_QNAME, ContractorExcludeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContractorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://zakupki.gov.ru/oos/printform/1", name = "eruzContractor")
    public JAXBElement<ContractorType> createEruzContractor(ContractorType value) {
        return new JAXBElement<ContractorType>(_EruzContractor_QNAME, ContractorType.class, null, value);
    }

}
