//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.02 at 03:51:32 PM MSK 
//


package ru.gov.zakupki.eruz.esmv.types._1;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.gov.zakupki.eruz.esmv.types._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.gov.zakupki.eruz.esmv.types._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TSignedData }
     * 
     */
    public TSignedData createTSignedData() {
        return new TSignedData();
    }

    /**
     * Create an instance of {@link TRequestPA }
     * 
     */
    public TRequestPA createTRequestPA() {
        return new TRequestPA();
    }

    /**
     * Create an instance of {@link TRequestPA.PrintFormFieldsInfo }
     * 
     */
    public TRequestPA.PrintFormFieldsInfo createTRequestPAPrintFormFieldsInfo() {
        return new TRequestPA.PrintFormFieldsInfo();
    }

    /**
     * Create an instance of {@link TRequestPA.FoundationInfo }
     * 
     */
    public TRequestPA.FoundationInfo createTRequestPAFoundationInfo() {
        return new TRequestPA.FoundationInfo();
    }

    /**
     * Create an instance of {@link TIndividualPerson }
     * 
     */
    public TIndividualPerson createTIndividualPerson() {
        return new TIndividualPerson();
    }

    /**
     * Create an instance of {@link TIndividualPerson.HeadsInfo }
     * 
     */
    public TIndividualPerson.HeadsInfo createTIndividualPersonHeadsInfo() {
        return new TIndividualPerson.HeadsInfo();
    }

    /**
     * Create an instance of {@link TIndividualPerson.AdressInfo }
     * 
     */
    public TIndividualPerson.AdressInfo createTIndividualPersonAdressInfo() {
        return new TIndividualPerson.AdressInfo();
    }

    /**
     * Create an instance of {@link TIndividualPerson.OKVEDs }
     * 
     */
    public TIndividualPerson.OKVEDs createTIndividualPersonOKVEDs() {
        return new TIndividualPerson.OKVEDs();
    }

    /**
     * Create an instance of {@link TLegalEntity }
     * 
     */
    public TLegalEntity createTLegalEntity() {
        return new TLegalEntity();
    }

    /**
     * Create an instance of {@link TLegalEntity.HeadsInfo }
     * 
     */
    public TLegalEntity.HeadsInfo createTLegalEntityHeadsInfo() {
        return new TLegalEntity.HeadsInfo();
    }

    /**
     * Create an instance of {@link TLegalEntity.AdressInfo }
     * 
     */
    public TLegalEntity.AdressInfo createTLegalEntityAdressInfo() {
        return new TLegalEntity.AdressInfo();
    }

    /**
     * Create an instance of {@link TLegalEntity.OKVEDs }
     * 
     */
    public TLegalEntity.OKVEDs createTLegalEntityOKVEDs() {
        return new TLegalEntity.OKVEDs();
    }

    /**
     * Create an instance of {@link TAdressRF }
     * 
     */
    public TAdressRF createTAdressRF() {
        return new TAdressRF();
    }

    /**
     * Create an instance of {@link TRequestResultPA }
     * 
     */
    public TRequestResultPA createTRequestResultPA() {
        return new TRequestResultPA();
    }

    /**
     * Create an instance of {@link TRequestResultPA.NotMatchOrder }
     * 
     */
    public TRequestResultPA.NotMatchOrder createTRequestResultPANotMatchOrder() {
        return new TRequestResultPA.NotMatchOrder();
    }

    /**
     * Create an instance of {@link TStatus }
     * 
     */
    public TStatus createTStatus() {
        return new TStatus();
    }

    /**
     * Create an instance of {@link TExecutor }
     * 
     */
    public TExecutor createTExecutor() {
        return new TExecutor();
    }

    /**
     * Create an instance of {@link TBudgetFunds }
     * 
     */
    public TBudgetFunds createTBudgetFunds() {
        return new TBudgetFunds();
    }

    /**
     * Create an instance of {@link TOKSMRef }
     * 
     */
    public TOKSMRef createTOKSMRef() {
        return new TOKSMRef();
    }

    /**
     * Create an instance of {@link TClient }
     * 
     */
    public TClient createTClient() {
        return new TClient();
    }

    /**
     * Create an instance of {@link TOKOPFRef }
     * 
     */
    public TOKOPFRef createTOKOPFRef() {
        return new TOKOPFRef();
    }

    /**
     * Create an instance of {@link TOKPORef }
     * 
     */
    public TOKPORef createTOKPORef() {
        return new TOKPORef();
    }

    /**
     * Create an instance of {@link TConfirm }
     * 
     */
    public TConfirm createTConfirm() {
        return new TConfirm();
    }

    /**
     * Create an instance of {@link TViolation }
     * 
     */
    public TViolation createTViolation() {
        return new TViolation();
    }

    /**
     * Create an instance of {@link TSignatureInfo }
     * 
     */
    public TSignatureInfo createTSignatureInfo() {
        return new TSignatureInfo();
    }

    /**
     * Create an instance of {@link TOKTMORef }
     * 
     */
    public TOKTMORef createTOKTMORef() {
        return new TOKTMORef();
    }

    /**
     * Create an instance of {@link TOKFSRef }
     * 
     */
    public TOKFSRef createTOKFSRef() {
        return new TOKFSRef();
    }

    /**
     * Create an instance of {@link TOKVEDRef }
     * 
     */
    public TOKVEDRef createTOKVEDRef() {
        return new TOKVEDRef();
    }

    /**
     * Create an instance of {@link TPerson }
     * 
     */
    public TPerson createTPerson() {
        return new TPerson();
    }

    /**
     * Create an instance of {@link TGRBS }
     * 
     */
    public TGRBS createTGRBS() {
        return new TGRBS();
    }

    /**
     * Create an instance of {@link TConfirmASinc }
     * 
     */
    public TConfirmASinc createTConfirmASinc() {
        return new TConfirmASinc();
    }

    /**
     * Create an instance of {@link TConfirmSinc }
     * 
     */
    public TConfirmSinc createTConfirmSinc() {
        return new TConfirmSinc();
    }

    /**
     * Create an instance of {@link TParams }
     * 
     */
    public TParams createTParams() {
        return new TParams();
    }

    /**
     * Create an instance of {@link TParam }
     * 
     */
    public TParam createTParam() {
        return new TParam();
    }

    /**
     * Create an instance of {@link TSignedData.Signature }
     * 
     */
    public TSignedData.Signature createTSignedDataSignature() {
        return new TSignedData.Signature();
    }

    /**
     * Create an instance of {@link TRequestPA.CommonInfo }
     * 
     */
    public TRequestPA.CommonInfo createTRequestPACommonInfo() {
        return new TRequestPA.CommonInfo();
    }

    /**
     * Create an instance of {@link TRequestPA.ContractorInfo }
     * 
     */
    public TRequestPA.ContractorInfo createTRequestPAContractorInfo() {
        return new TRequestPA.ContractorInfo();
    }

    /**
     * Create an instance of {@link TRequestPA.SignatoriesInfo }
     * 
     */
    public TRequestPA.SignatoriesInfo createTRequestPASignatoriesInfo() {
        return new TRequestPA.SignatoriesInfo();
    }

    /**
     * Create an instance of {@link TRequestPA.PrintFormFieldsInfo.TOFKInfo }
     * 
     */
    public TRequestPA.PrintFormFieldsInfo.TOFKInfo createTRequestPAPrintFormFieldsInfoTOFKInfo() {
        return new TRequestPA.PrintFormFieldsInfo.TOFKInfo();
    }

    /**
     * Create an instance of {@link TRequestPA.FoundationInfo.OrganizationInfo }
     * 
     */
    public TRequestPA.FoundationInfo.OrganizationInfo createTRequestPAFoundationInfoOrganizationInfo() {
        return new TRequestPA.FoundationInfo.OrganizationInfo();
    }

    /**
     * Create an instance of {@link TRequestPA.FoundationInfo.ContractInfo }
     * 
     */
    public TRequestPA.FoundationInfo.ContractInfo createTRequestPAFoundationInfoContractInfo() {
        return new TRequestPA.FoundationInfo.ContractInfo();
    }

    /**
     * Create an instance of {@link TIndividualPerson.ChiefAccountantInfo }
     * 
     */
    public TIndividualPerson.ChiefAccountantInfo createTIndividualPersonChiefAccountantInfo() {
        return new TIndividualPerson.ChiefAccountantInfo();
    }

    /**
     * Create an instance of {@link TIndividualPerson.HeadsInfo.HeadInfo }
     * 
     */
    public TIndividualPerson.HeadsInfo.HeadInfo createTIndividualPersonHeadsInfoHeadInfo() {
        return new TIndividualPerson.HeadsInfo.HeadInfo();
    }

    /**
     * Create an instance of {@link TIndividualPerson.AdressInfo.AdressFSInfo }
     * 
     */
    public TIndividualPerson.AdressInfo.AdressFSInfo createTIndividualPersonAdressInfoAdressFSInfo() {
        return new TIndividualPerson.AdressInfo.AdressFSInfo();
    }

    /**
     * Create an instance of {@link TIndividualPerson.OKVEDs.OKVED }
     * 
     */
    public TIndividualPerson.OKVEDs.OKVED createTIndividualPersonOKVEDsOKVED() {
        return new TIndividualPerson.OKVEDs.OKVED();
    }

    /**
     * Create an instance of {@link TLegalEntity.ChiefAccountantInfo }
     * 
     */
    public TLegalEntity.ChiefAccountantInfo createTLegalEntityChiefAccountantInfo() {
        return new TLegalEntity.ChiefAccountantInfo();
    }

    /**
     * Create an instance of {@link TLegalEntity.HeadsInfo.HeadInfo }
     * 
     */
    public TLegalEntity.HeadsInfo.HeadInfo createTLegalEntityHeadsInfoHeadInfo() {
        return new TLegalEntity.HeadsInfo.HeadInfo();
    }

    /**
     * Create an instance of {@link TLegalEntity.AdressInfo.AdressFSInfo }
     * 
     */
    public TLegalEntity.AdressInfo.AdressFSInfo createTLegalEntityAdressInfoAdressFSInfo() {
        return new TLegalEntity.AdressInfo.AdressFSInfo();
    }

    /**
     * Create an instance of {@link TLegalEntity.OKVEDs.OKVED }
     * 
     */
    public TLegalEntity.OKVEDs.OKVED createTLegalEntityOKVEDsOKVED() {
        return new TLegalEntity.OKVEDs.OKVED();
    }

    /**
     * Create an instance of {@link TAdressRF.RegionInfo }
     * 
     */
    public TAdressRF.RegionInfo createTAdressRFRegionInfo() {
        return new TAdressRF.RegionInfo();
    }

    /**
     * Create an instance of {@link TAdressRF.AreaInfo }
     * 
     */
    public TAdressRF.AreaInfo createTAdressRFAreaInfo() {
        return new TAdressRF.AreaInfo();
    }

    /**
     * Create an instance of {@link TAdressRF.CityInfo }
     * 
     */
    public TAdressRF.CityInfo createTAdressRFCityInfo() {
        return new TAdressRF.CityInfo();
    }

    /**
     * Create an instance of {@link TAdressRF.SettlementInfo }
     * 
     */
    public TAdressRF.SettlementInfo createTAdressRFSettlementInfo() {
        return new TAdressRF.SettlementInfo();
    }

    /**
     * Create an instance of {@link TAdressRF.ShortStreetInfo }
     * 
     */
    public TAdressRF.ShortStreetInfo createTAdressRFShortStreetInfo() {
        return new TAdressRF.ShortStreetInfo();
    }

    /**
     * Create an instance of {@link TRequestResultPA.Violations }
     * 
     */
    public TRequestResultPA.Violations createTRequestResultPAViolations() {
        return new TRequestResultPA.Violations();
    }

    /**
     * Create an instance of {@link TRequestResultPA.SuccessRegister }
     * 
     */
    public TRequestResultPA.SuccessRegister createTRequestResultPASuccessRegister() {
        return new TRequestResultPA.SuccessRegister();
    }

    /**
     * Create an instance of {@link TRequestResultPA.NotMatchOrder.PrintFormFieldsInfo }
     * 
     */
    public TRequestResultPA.NotMatchOrder.PrintFormFieldsInfo createTRequestResultPANotMatchOrderPrintFormFieldsInfo() {
        return new TRequestResultPA.NotMatchOrder.PrintFormFieldsInfo();
    }

}
