//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.02 at 04:14:17 PM MSK 
//


package ru.gov.zakupki.eruz.esmv.types._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Тип: Адрес РФ
 * 
 * <p>Java class for tAdressRF complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tAdressRF">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="kladrCode" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tKLADRCode" minOccurs="0"/>
 *         &lt;element name="zip" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tZip" minOccurs="0"/>
 *         &lt;element name="regionCode" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tRegionCode" minOccurs="0"/>
 *         &lt;element name="regionInfo" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="fullName" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tText1000" minOccurs="0"/>
 *                   &lt;element name="type" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tKLADRObjCode" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="areaInfo" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="fullName" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tText1000" minOccurs="0"/>
 *                   &lt;element name="type" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tKLADRObjCode" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="cityInfo" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="fullName" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tText1000" minOccurs="0"/>
 *                   &lt;element name="type" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tKLADRObjCode" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="settlementInfo" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="fullName" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tText1000" minOccurs="0"/>
 *                   &lt;element name="type" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tKLADRObjCode" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="shortStreetInfo" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="fullName" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tText1000" minOccurs="0"/>
 *                   &lt;element name="type" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tKLADRObjCode" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="building" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tKLADRObjName" minOccurs="0"/>
 *         &lt;element name="housing" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tKLADRObjName" minOccurs="0"/>
 *         &lt;element name="flat" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tKLADRObjName" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tAdressRF", propOrder = {
    "kladrCode",
    "zip",
    "regionCode",
    "regionInfo",
    "areaInfo",
    "cityInfo",
    "settlementInfo",
    "shortStreetInfo",
    "building",
    "housing",
    "flat"
})
public class TAdressRF {

    protected String kladrCode;
    protected String zip;
    protected String regionCode;
    protected TAdressRF.RegionInfo regionInfo;
    protected TAdressRF.AreaInfo areaInfo;
    protected TAdressRF.CityInfo cityInfo;
    protected TAdressRF.SettlementInfo settlementInfo;
    protected TAdressRF.ShortStreetInfo shortStreetInfo;
    protected String building;
    protected String housing;
    protected String flat;

    /**
     * Gets the value of the kladrCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKladrCode() {
        return kladrCode;
    }

    /**
     * Sets the value of the kladrCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKladrCode(String value) {
        this.kladrCode = value;
    }

    /**
     * Gets the value of the zip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZip() {
        return zip;
    }

    /**
     * Sets the value of the zip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZip(String value) {
        this.zip = value;
    }

    /**
     * Gets the value of the regionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegionCode() {
        return regionCode;
    }

    /**
     * Sets the value of the regionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegionCode(String value) {
        this.regionCode = value;
    }

    /**
     * Gets the value of the regionInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TAdressRF.RegionInfo }
     *     
     */
    public TAdressRF.RegionInfo getRegionInfo() {
        return regionInfo;
    }

    /**
     * Sets the value of the regionInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAdressRF.RegionInfo }
     *     
     */
    public void setRegionInfo(TAdressRF.RegionInfo value) {
        this.regionInfo = value;
    }

    /**
     * Gets the value of the areaInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TAdressRF.AreaInfo }
     *     
     */
    public TAdressRF.AreaInfo getAreaInfo() {
        return areaInfo;
    }

    /**
     * Sets the value of the areaInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAdressRF.AreaInfo }
     *     
     */
    public void setAreaInfo(TAdressRF.AreaInfo value) {
        this.areaInfo = value;
    }

    /**
     * Gets the value of the cityInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TAdressRF.CityInfo }
     *     
     */
    public TAdressRF.CityInfo getCityInfo() {
        return cityInfo;
    }

    /**
     * Sets the value of the cityInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAdressRF.CityInfo }
     *     
     */
    public void setCityInfo(TAdressRF.CityInfo value) {
        this.cityInfo = value;
    }

    /**
     * Gets the value of the settlementInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TAdressRF.SettlementInfo }
     *     
     */
    public TAdressRF.SettlementInfo getSettlementInfo() {
        return settlementInfo;
    }

    /**
     * Sets the value of the settlementInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAdressRF.SettlementInfo }
     *     
     */
    public void setSettlementInfo(TAdressRF.SettlementInfo value) {
        this.settlementInfo = value;
    }

    /**
     * Gets the value of the shortStreetInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TAdressRF.ShortStreetInfo }
     *     
     */
    public TAdressRF.ShortStreetInfo getShortStreetInfo() {
        return shortStreetInfo;
    }

    /**
     * Sets the value of the shortStreetInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAdressRF.ShortStreetInfo }
     *     
     */
    public void setShortStreetInfo(TAdressRF.ShortStreetInfo value) {
        this.shortStreetInfo = value;
    }

    /**
     * Gets the value of the building property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBuilding() {
        return building;
    }

    /**
     * Sets the value of the building property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBuilding(String value) {
        this.building = value;
    }

    /**
     * Gets the value of the housing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHousing() {
        return housing;
    }

    /**
     * Sets the value of the housing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHousing(String value) {
        this.housing = value;
    }

    /**
     * Gets the value of the flat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlat() {
        return flat;
    }

    /**
     * Sets the value of the flat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlat(String value) {
        this.flat = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="fullName" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tText1000" minOccurs="0"/>
     *         &lt;element name="type" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tKLADRObjCode" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fullName",
        "type"
    })
    public static class AreaInfo {

        protected String fullName;
        protected String type;

        /**
         * Gets the value of the fullName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFullName() {
            return fullName;
        }

        /**
         * Sets the value of the fullName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFullName(String value) {
            this.fullName = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="fullName" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tText1000" minOccurs="0"/>
     *         &lt;element name="type" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tKLADRObjCode" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fullName",
        "type"
    })
    public static class CityInfo {

        protected String fullName;
        protected String type;

        /**
         * Gets the value of the fullName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFullName() {
            return fullName;
        }

        /**
         * Sets the value of the fullName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFullName(String value) {
            this.fullName = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="fullName" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tText1000" minOccurs="0"/>
     *         &lt;element name="type" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tKLADRObjCode" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fullName",
        "type"
    })
    public static class RegionInfo {

        protected String fullName;
        protected String type;

        /**
         * Gets the value of the fullName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFullName() {
            return fullName;
        }

        /**
         * Sets the value of the fullName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFullName(String value) {
            this.fullName = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="fullName" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tText1000" minOccurs="0"/>
     *         &lt;element name="type" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tKLADRObjCode" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fullName",
        "type"
    })
    public static class SettlementInfo {

        protected String fullName;
        protected String type;

        /**
         * Gets the value of the fullName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFullName() {
            return fullName;
        }

        /**
         * Sets the value of the fullName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFullName(String value) {
            this.fullName = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="fullName" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tText1000" minOccurs="0"/>
     *         &lt;element name="type" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tKLADRObjCode" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fullName",
        "type"
    })
    public static class ShortStreetInfo {

        protected String fullName;
        protected String type;

        /**
         * Gets the value of the fullName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFullName() {
            return fullName;
        }

        /**
         * Sets the value of the fullName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFullName(String value) {
            this.fullName = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

    }

}
