//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.02 at 04:14:17 PM MSK 
//


package ru.gov.zakupki.eruz.esmv.types._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Тип: Клиент в протоколе об отказе в открытии ЛС и квитанции
 * 
 * <p>Java class for tClient complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tClient">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="consRegistryNum" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tSvRCode"/>
 *           &lt;element name="NUBP" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tNUBP"/>
 *         &lt;/choice>
 *         &lt;element name="fullName" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tText2000" minOccurs="0"/>
 *         &lt;element name="personalAccountNumber" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tAccountNumber"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tClient", propOrder = {
    "consRegistryNum",
    "nubp",
    "fullName",
    "personalAccountNumber"
})
public class TClient {

    protected String consRegistryNum;
    @XmlElement(name = "NUBP")
    protected String nubp;
    protected String fullName;
    @XmlElement(required = true)
    protected String personalAccountNumber;

    /**
     * Gets the value of the consRegistryNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsRegistryNum() {
        return consRegistryNum;
    }

    /**
     * Sets the value of the consRegistryNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsRegistryNum(String value) {
        this.consRegistryNum = value;
    }

    /**
     * Gets the value of the nubp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNUBP() {
        return nubp;
    }

    /**
     * Sets the value of the nubp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNUBP(String value) {
        this.nubp = value;
    }

    /**
     * Gets the value of the fullName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * Sets the value of the fullName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullName(String value) {
        this.fullName = value;
    }

    /**
     * Gets the value of the personalAccountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonalAccountNumber() {
        return personalAccountNumber;
    }

    /**
     * Sets the value of the personalAccountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonalAccountNumber(String value) {
        this.personalAccountNumber = value;
    }

}
