//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.02 at 04:13:19 PM MSK 
//


package ru.gov.zakupki.eruz.esmv.types._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Тип: Результат рассмотрения заявления на резервирование/открытие лицевого счёта
 * 
 * <p>Java class for tRequestResultPA complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tRequestResultPA">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="refId" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tGUID"/>
 *         &lt;element name="TOFK" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tTOFKCode"/>
 *         &lt;element name="TOFKName" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tText2000" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="violations">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="violation" type="{http://zakupki.gov.ru/eruz/esmv/types/1}tViolation" maxOccurs="unbounded"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="successRegister">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="Id" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tGUID"/>
 *                     &lt;element name="receiptNumber" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tProtocolNumber"/>
 *                     &lt;element name="registrationDT" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                     &lt;element name="statementEDoc" type="{http://zakupki.gov.ru/eruz/esmv/types/1}tSignedData"/>
 *                     &lt;element name="clientInfo" type="{http://zakupki.gov.ru/eruz/esmv/types/1}tClient"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="notMatchOrder">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="Id" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tGUID"/>
 *                     &lt;element name="protocolNumber" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tProtocolNumber"/>
 *                     &lt;element name="createDT" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                     &lt;element name="rejectionReason" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tText2000"/>
 *                     &lt;element name="executorInfo" type="{http://zakupki.gov.ru/eruz/esmv/types/1}tExecutor"/>
 *                     &lt;element name="notMatchEDoc" type="{http://zakupki.gov.ru/eruz/esmv/types/1}tSignedData"/>
 *                     &lt;element name="clientInfo" type="{http://zakupki.gov.ru/eruz/esmv/types/1}tClient"/>
 *                     &lt;element name="printFormFieldsInfo" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence minOccurs="0">
 *                               &lt;element name="budgetName" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tText2000" minOccurs="0"/>
 *                               &lt;element name="requestNum" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tApplicationNum" minOccurs="0"/>
 *                               &lt;element name="generationDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                               &lt;element name="requestAcceptDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="schemeVersion" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tRequestResultPA", propOrder = {
    "refId",
    "tofk",
    "tofkName",
    "violations",
    "successRegister",
    "notMatchOrder"
})
public class TRequestResultPA {

    @XmlElement(required = true)
    protected String refId;
    @XmlElement(name = "TOFK", required = true)
    protected String tofk;
    @XmlElement(name = "TOFKName")
    protected String tofkName;
    protected TRequestResultPA.Violations violations;
    protected TRequestResultPA.SuccessRegister successRegister;
    protected TRequestResultPA.NotMatchOrder notMatchOrder;
    @XmlAttribute(name = "schemeVersion", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String schemeVersion;

    /**
     * Gets the value of the refId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefId() {
        return refId;
    }

    /**
     * Sets the value of the refId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefId(String value) {
        this.refId = value;
    }

    /**
     * Gets the value of the tofk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTOFK() {
        return tofk;
    }

    /**
     * Sets the value of the tofk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOFK(String value) {
        this.tofk = value;
    }

    /**
     * Gets the value of the tofkName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTOFKName() {
        return tofkName;
    }

    /**
     * Sets the value of the tofkName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOFKName(String value) {
        this.tofkName = value;
    }

    /**
     * Gets the value of the violations property.
     * 
     * @return
     *     possible object is
     *     {@link TRequestResultPA.Violations }
     *     
     */
    public TRequestResultPA.Violations getViolations() {
        return violations;
    }

    /**
     * Sets the value of the violations property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRequestResultPA.Violations }
     *     
     */
    public void setViolations(TRequestResultPA.Violations value) {
        this.violations = value;
    }

    /**
     * Gets the value of the successRegister property.
     * 
     * @return
     *     possible object is
     *     {@link TRequestResultPA.SuccessRegister }
     *     
     */
    public TRequestResultPA.SuccessRegister getSuccessRegister() {
        return successRegister;
    }

    /**
     * Sets the value of the successRegister property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRequestResultPA.SuccessRegister }
     *     
     */
    public void setSuccessRegister(TRequestResultPA.SuccessRegister value) {
        this.successRegister = value;
    }

    /**
     * Gets the value of the notMatchOrder property.
     * 
     * @return
     *     possible object is
     *     {@link TRequestResultPA.NotMatchOrder }
     *     
     */
    public TRequestResultPA.NotMatchOrder getNotMatchOrder() {
        return notMatchOrder;
    }

    /**
     * Sets the value of the notMatchOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRequestResultPA.NotMatchOrder }
     *     
     */
    public void setNotMatchOrder(TRequestResultPA.NotMatchOrder value) {
        this.notMatchOrder = value;
    }

    /**
     * Gets the value of the schemeVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemeVersion() {
        return schemeVersion;
    }

    /**
     * Sets the value of the schemeVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemeVersion(String value) {
        this.schemeVersion = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Id" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tGUID"/>
     *         &lt;element name="protocolNumber" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tProtocolNumber"/>
     *         &lt;element name="createDT" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="rejectionReason" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tText2000"/>
     *         &lt;element name="executorInfo" type="{http://zakupki.gov.ru/eruz/esmv/types/1}tExecutor"/>
     *         &lt;element name="notMatchEDoc" type="{http://zakupki.gov.ru/eruz/esmv/types/1}tSignedData"/>
     *         &lt;element name="clientInfo" type="{http://zakupki.gov.ru/eruz/esmv/types/1}tClient"/>
     *         &lt;element name="printFormFieldsInfo" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence minOccurs="0">
     *                   &lt;element name="budgetName" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tText2000" minOccurs="0"/>
     *                   &lt;element name="requestNum" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tApplicationNum" minOccurs="0"/>
     *                   &lt;element name="generationDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *                   &lt;element name="requestAcceptDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "protocolNumber",
        "createDT",
        "rejectionReason",
        "executorInfo",
        "notMatchEDoc",
        "clientInfo",
        "printFormFieldsInfo"
    })
    public static class NotMatchOrder {

        @XmlElement(name = "Id", required = true)
        protected String id;
        @XmlElement(required = true)
        protected String protocolNumber;
        @XmlElement(required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar createDT;
        @XmlElement(required = true)
        protected String rejectionReason;
        @XmlElement(required = true)
        protected TExecutor executorInfo;
        @XmlElement(required = true)
        protected TSignedData notMatchEDoc;
        @XmlElement(required = true)
        protected TClient clientInfo;
        protected TRequestResultPA.NotMatchOrder.PrintFormFieldsInfo printFormFieldsInfo;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the protocolNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProtocolNumber() {
            return protocolNumber;
        }

        /**
         * Sets the value of the protocolNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProtocolNumber(String value) {
            this.protocolNumber = value;
        }

        /**
         * Gets the value of the createDT property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getCreateDT() {
            return createDT;
        }

        /**
         * Sets the value of the createDT property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setCreateDT(XMLGregorianCalendar value) {
            this.createDT = value;
        }

        /**
         * Gets the value of the rejectionReason property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRejectionReason() {
            return rejectionReason;
        }

        /**
         * Sets the value of the rejectionReason property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRejectionReason(String value) {
            this.rejectionReason = value;
        }

        /**
         * Gets the value of the executorInfo property.
         * 
         * @return
         *     possible object is
         *     {@link TExecutor }
         *     
         */
        public TExecutor getExecutorInfo() {
            return executorInfo;
        }

        /**
         * Sets the value of the executorInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link TExecutor }
         *     
         */
        public void setExecutorInfo(TExecutor value) {
            this.executorInfo = value;
        }

        /**
         * Gets the value of the notMatchEDoc property.
         * 
         * @return
         *     possible object is
         *     {@link TSignedData }
         *     
         */
        public TSignedData getNotMatchEDoc() {
            return notMatchEDoc;
        }

        /**
         * Sets the value of the notMatchEDoc property.
         * 
         * @param value
         *     allowed object is
         *     {@link TSignedData }
         *     
         */
        public void setNotMatchEDoc(TSignedData value) {
            this.notMatchEDoc = value;
        }

        /**
         * Gets the value of the clientInfo property.
         * 
         * @return
         *     possible object is
         *     {@link TClient }
         *     
         */
        public TClient getClientInfo() {
            return clientInfo;
        }

        /**
         * Sets the value of the clientInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link TClient }
         *     
         */
        public void setClientInfo(TClient value) {
            this.clientInfo = value;
        }

        /**
         * Gets the value of the printFormFieldsInfo property.
         * 
         * @return
         *     possible object is
         *     {@link TRequestResultPA.NotMatchOrder.PrintFormFieldsInfo }
         *     
         */
        public TRequestResultPA.NotMatchOrder.PrintFormFieldsInfo getPrintFormFieldsInfo() {
            return printFormFieldsInfo;
        }

        /**
         * Sets the value of the printFormFieldsInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link TRequestResultPA.NotMatchOrder.PrintFormFieldsInfo }
         *     
         */
        public void setPrintFormFieldsInfo(TRequestResultPA.NotMatchOrder.PrintFormFieldsInfo value) {
            this.printFormFieldsInfo = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence minOccurs="0">
         *         &lt;element name="budgetName" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tText2000" minOccurs="0"/>
         *         &lt;element name="requestNum" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tApplicationNum" minOccurs="0"/>
         *         &lt;element name="generationDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
         *         &lt;element name="requestAcceptDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "budgetName",
            "requestNum",
            "generationDate",
            "requestAcceptDate"
        })
        public static class PrintFormFieldsInfo {

            protected String budgetName;
            protected String requestNum;
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar generationDate;
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar requestAcceptDate;

            /**
             * Gets the value of the budgetName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBudgetName() {
                return budgetName;
            }

            /**
             * Sets the value of the budgetName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBudgetName(String value) {
                this.budgetName = value;
            }

            /**
             * Gets the value of the requestNum property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRequestNum() {
                return requestNum;
            }

            /**
             * Sets the value of the requestNum property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRequestNum(String value) {
                this.requestNum = value;
            }

            /**
             * Gets the value of the generationDate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getGenerationDate() {
                return generationDate;
            }

            /**
             * Sets the value of the generationDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setGenerationDate(XMLGregorianCalendar value) {
                this.generationDate = value;
            }

            /**
             * Gets the value of the requestAcceptDate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getRequestAcceptDate() {
                return requestAcceptDate;
            }

            /**
             * Sets the value of the requestAcceptDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setRequestAcceptDate(XMLGregorianCalendar value) {
                this.requestAcceptDate = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Id" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tGUID"/>
     *         &lt;element name="receiptNumber" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tProtocolNumber"/>
     *         &lt;element name="registrationDT" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="statementEDoc" type="{http://zakupki.gov.ru/eruz/esmv/types/1}tSignedData"/>
     *         &lt;element name="clientInfo" type="{http://zakupki.gov.ru/eruz/esmv/types/1}tClient"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "receiptNumber",
        "registrationDT",
        "statementEDoc",
        "clientInfo"
    })
    public static class SuccessRegister {

        @XmlElement(name = "Id", required = true)
        protected String id;
        @XmlElement(required = true)
        protected String receiptNumber;
        @XmlElement(required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar registrationDT;
        @XmlElement(required = true)
        protected TSignedData statementEDoc;
        @XmlElement(required = true)
        protected TClient clientInfo;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the receiptNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReceiptNumber() {
            return receiptNumber;
        }

        /**
         * Sets the value of the receiptNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReceiptNumber(String value) {
            this.receiptNumber = value;
        }

        /**
         * Gets the value of the registrationDT property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getRegistrationDT() {
            return registrationDT;
        }

        /**
         * Sets the value of the registrationDT property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setRegistrationDT(XMLGregorianCalendar value) {
            this.registrationDT = value;
        }

        /**
         * Gets the value of the statementEDoc property.
         * 
         * @return
         *     possible object is
         *     {@link TSignedData }
         *     
         */
        public TSignedData getStatementEDoc() {
            return statementEDoc;
        }

        /**
         * Sets the value of the statementEDoc property.
         * 
         * @param value
         *     allowed object is
         *     {@link TSignedData }
         *     
         */
        public void setStatementEDoc(TSignedData value) {
            this.statementEDoc = value;
        }

        /**
         * Gets the value of the clientInfo property.
         * 
         * @return
         *     possible object is
         *     {@link TClient }
         *     
         */
        public TClient getClientInfo() {
            return clientInfo;
        }

        /**
         * Sets the value of the clientInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link TClient }
         *     
         */
        public void setClientInfo(TClient value) {
            this.clientInfo = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="violation" type="{http://zakupki.gov.ru/eruz/esmv/types/1}tViolation" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "violation"
    })
    public static class Violations {

        @XmlElement(required = true)
        protected List<TViolation> violation;

        /**
         * Gets the value of the violation property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the violation property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getViolation().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TViolation }
         * 
         * 
         */
        public List<TViolation> getViolation() {
            if (violation == null) {
                violation = new ArrayList<TViolation>();
            }
            return this.violation;
        }

    }

}
