//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.02 at 03:51:32 PM MSK 
//


package ru.gov.zakupki.eruz.esmv.types._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Тип: Заявление на резервирование/открытие лицевого счёта
 * 
 * <p>Java class for tRequestPA complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tRequestPA">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tGUID"/>
 *         &lt;element name="commonInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="requestNum" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tApplicationNum" minOccurs="0"/>
 *                   &lt;element name="requestType" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tRequestPAEnum"/>
 *                   &lt;element name="generationDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="budget" type="{http://zakupki.gov.ru/eruz/esmv/types/1}tBudgetFunds" minOccurs="0"/>
 *                   &lt;element name="budgetLevel" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tBudgetLevel" minOccurs="0"/>
 *                   &lt;element name="personalAccount" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tAccountNumber" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="contractorInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="legalEntityInfo" type="{http://zakupki.gov.ru/eruz/esmv/types/1}tLegalEntity"/>
 *                   &lt;element name="individualPersonInfo" type="{http://zakupki.gov.ru/eruz/esmv/types/1}tIndividualPerson"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="foundationInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="organizationInfo" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;choice minOccurs="0">
 *                               &lt;element name="consRegistryNum" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tSvRCode"/>
 *                               &lt;element name="NUBP" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tNUBP"/>
 *                             &lt;/choice>
 *                             &lt;element name="INN" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tINNOrganization" minOccurs="0"/>
 *                             &lt;element name="fullName" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tText2000" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="GRBSCode" type="{http://zakupki.gov.ru/eruz/esmv/types/1}tGRBS"/>
 *                   &lt;element name="contractInfo" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="number" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tContractTextCode" minOccurs="0"/>
 *                             &lt;element name="IGK" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tIGK" minOccurs="0"/>
 *                             &lt;element name="conclusionDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                             &lt;element name="regNum" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tContractRegNum" minOccurs="0"/>
 *                             &lt;element name="link" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tText2000" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="signatoriesInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="headSignatureInfo" type="{http://zakupki.gov.ru/eruz/esmv/types/1}tSignatureInfo"/>
 *                   &lt;element name="accountantSignatureInfo" type="{http://zakupki.gov.ru/eruz/esmv/types/1}tSignatureInfo" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="printFormInfo" type="{http://zakupki.gov.ru/eruz/esmv/types/1}tSignedData"/>
 *         &lt;element name="printFormFieldsInfo" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence minOccurs="0">
 *                   &lt;element name="TOFKInfo" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence minOccurs="0">
 *                             &lt;element name="code" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tTOFKCode" minOccurs="0"/>
 *                             &lt;element name="name" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tText2000" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="foundation" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tText2000" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="schemeVersion" use="required" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tSchemeVersion" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tRequestPA", propOrder = {
    "id",
    "commonInfo",
    "contractorInfo",
    "foundationInfo",
    "signatoriesInfo",
    "printFormInfo",
    "printFormFieldsInfo"
})
public class TRequestPA {

    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    protected TRequestPA.CommonInfo commonInfo;
    @XmlElement(required = true)
    protected TRequestPA.ContractorInfo contractorInfo;
    @XmlElement(required = true)
    protected TRequestPA.FoundationInfo foundationInfo;
    @XmlElement(required = true)
    protected TRequestPA.SignatoriesInfo signatoriesInfo;
    @XmlElement(required = true)
    protected TSignedData printFormInfo;
    protected TRequestPA.PrintFormFieldsInfo printFormFieldsInfo;
    @XmlAttribute(name = "schemeVersion", required = true)
    protected String schemeVersion;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the commonInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TRequestPA.CommonInfo }
     *     
     */
    public TRequestPA.CommonInfo getCommonInfo() {
        return commonInfo;
    }

    /**
     * Sets the value of the commonInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRequestPA.CommonInfo }
     *     
     */
    public void setCommonInfo(TRequestPA.CommonInfo value) {
        this.commonInfo = value;
    }

    /**
     * Gets the value of the contractorInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TRequestPA.ContractorInfo }
     *     
     */
    public TRequestPA.ContractorInfo getContractorInfo() {
        return contractorInfo;
    }

    /**
     * Sets the value of the contractorInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRequestPA.ContractorInfo }
     *     
     */
    public void setContractorInfo(TRequestPA.ContractorInfo value) {
        this.contractorInfo = value;
    }

    /**
     * Gets the value of the foundationInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TRequestPA.FoundationInfo }
     *     
     */
    public TRequestPA.FoundationInfo getFoundationInfo() {
        return foundationInfo;
    }

    /**
     * Sets the value of the foundationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRequestPA.FoundationInfo }
     *     
     */
    public void setFoundationInfo(TRequestPA.FoundationInfo value) {
        this.foundationInfo = value;
    }

    /**
     * Gets the value of the signatoriesInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TRequestPA.SignatoriesInfo }
     *     
     */
    public TRequestPA.SignatoriesInfo getSignatoriesInfo() {
        return signatoriesInfo;
    }

    /**
     * Sets the value of the signatoriesInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRequestPA.SignatoriesInfo }
     *     
     */
    public void setSignatoriesInfo(TRequestPA.SignatoriesInfo value) {
        this.signatoriesInfo = value;
    }

    /**
     * Gets the value of the printFormInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TSignedData }
     *     
     */
    public TSignedData getPrintFormInfo() {
        return printFormInfo;
    }

    /**
     * Sets the value of the printFormInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSignedData }
     *     
     */
    public void setPrintFormInfo(TSignedData value) {
        this.printFormInfo = value;
    }

    /**
     * Gets the value of the printFormFieldsInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TRequestPA.PrintFormFieldsInfo }
     *     
     */
    public TRequestPA.PrintFormFieldsInfo getPrintFormFieldsInfo() {
        return printFormFieldsInfo;
    }

    /**
     * Sets the value of the printFormFieldsInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TRequestPA.PrintFormFieldsInfo }
     *     
     */
    public void setPrintFormFieldsInfo(TRequestPA.PrintFormFieldsInfo value) {
        this.printFormFieldsInfo = value;
    }

    /**
     * Gets the value of the schemeVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemeVersion() {
        return schemeVersion;
    }

    /**
     * Sets the value of the schemeVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemeVersion(String value) {
        this.schemeVersion = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="requestNum" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tApplicationNum" minOccurs="0"/>
     *         &lt;element name="requestType" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tRequestPAEnum"/>
     *         &lt;element name="generationDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="budget" type="{http://zakupki.gov.ru/eruz/esmv/types/1}tBudgetFunds" minOccurs="0"/>
     *         &lt;element name="budgetLevel" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tBudgetLevel" minOccurs="0"/>
     *         &lt;element name="personalAccount" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tAccountNumber" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "requestNum",
        "requestType",
        "generationDate",
        "budget",
        "budgetLevel",
        "personalAccount"
    })
    public static class CommonInfo {

        protected String requestNum;
        @XmlElement(required = true)
        protected String requestType;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar generationDate;
        protected TBudgetFunds budget;
        protected String budgetLevel;
        protected String personalAccount;

        /**
         * Gets the value of the requestNum property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRequestNum() {
            return requestNum;
        }

        /**
         * Sets the value of the requestNum property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRequestNum(String value) {
            this.requestNum = value;
        }

        /**
         * Gets the value of the requestType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRequestType() {
            return requestType;
        }

        /**
         * Sets the value of the requestType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRequestType(String value) {
            this.requestType = value;
        }

        /**
         * Gets the value of the generationDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getGenerationDate() {
            return generationDate;
        }

        /**
         * Sets the value of the generationDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setGenerationDate(XMLGregorianCalendar value) {
            this.generationDate = value;
        }

        /**
         * Gets the value of the budget property.
         * 
         * @return
         *     possible object is
         *     {@link TBudgetFunds }
         *     
         */
        public TBudgetFunds getBudget() {
            return budget;
        }

        /**
         * Sets the value of the budget property.
         * 
         * @param value
         *     allowed object is
         *     {@link TBudgetFunds }
         *     
         */
        public void setBudget(TBudgetFunds value) {
            this.budget = value;
        }

        /**
         * Gets the value of the budgetLevel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBudgetLevel() {
            return budgetLevel;
        }

        /**
         * Sets the value of the budgetLevel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBudgetLevel(String value) {
            this.budgetLevel = value;
        }

        /**
         * Gets the value of the personalAccount property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPersonalAccount() {
            return personalAccount;
        }

        /**
         * Sets the value of the personalAccount property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPersonalAccount(String value) {
            this.personalAccount = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="legalEntityInfo" type="{http://zakupki.gov.ru/eruz/esmv/types/1}tLegalEntity"/>
     *         &lt;element name="individualPersonInfo" type="{http://zakupki.gov.ru/eruz/esmv/types/1}tIndividualPerson"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "legalEntityInfo",
        "individualPersonInfo"
    })
    public static class ContractorInfo {

        protected TLegalEntity legalEntityInfo;
        protected TIndividualPerson individualPersonInfo;

        /**
         * Gets the value of the legalEntityInfo property.
         * 
         * @return
         *     possible object is
         *     {@link TLegalEntity }
         *     
         */
        public TLegalEntity getLegalEntityInfo() {
            return legalEntityInfo;
        }

        /**
         * Sets the value of the legalEntityInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link TLegalEntity }
         *     
         */
        public void setLegalEntityInfo(TLegalEntity value) {
            this.legalEntityInfo = value;
        }

        /**
         * Gets the value of the individualPersonInfo property.
         * 
         * @return
         *     possible object is
         *     {@link TIndividualPerson }
         *     
         */
        public TIndividualPerson getIndividualPersonInfo() {
            return individualPersonInfo;
        }

        /**
         * Sets the value of the individualPersonInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link TIndividualPerson }
         *     
         */
        public void setIndividualPersonInfo(TIndividualPerson value) {
            this.individualPersonInfo = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="organizationInfo" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;choice minOccurs="0">
     *                     &lt;element name="consRegistryNum" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tSvRCode"/>
     *                     &lt;element name="NUBP" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tNUBP"/>
     *                   &lt;/choice>
     *                   &lt;element name="INN" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tINNOrganization" minOccurs="0"/>
     *                   &lt;element name="fullName" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tText2000" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="GRBSCode" type="{http://zakupki.gov.ru/eruz/esmv/types/1}tGRBS"/>
     *         &lt;element name="contractInfo" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="number" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tContractTextCode" minOccurs="0"/>
     *                   &lt;element name="IGK" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tIGK" minOccurs="0"/>
     *                   &lt;element name="conclusionDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *                   &lt;element name="regNum" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tContractRegNum" minOccurs="0"/>
     *                   &lt;element name="link" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tText2000" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "organizationInfo",
        "grbsCode",
        "contractInfo"
    })
    public static class FoundationInfo {

        protected TRequestPA.FoundationInfo.OrganizationInfo organizationInfo;
        @XmlElement(name = "GRBSCode", required = true)
        protected TGRBS grbsCode;
        protected TRequestPA.FoundationInfo.ContractInfo contractInfo;

        /**
         * Gets the value of the organizationInfo property.
         * 
         * @return
         *     possible object is
         *     {@link TRequestPA.FoundationInfo.OrganizationInfo }
         *     
         */
        public TRequestPA.FoundationInfo.OrganizationInfo getOrganizationInfo() {
            return organizationInfo;
        }

        /**
         * Sets the value of the organizationInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link TRequestPA.FoundationInfo.OrganizationInfo }
         *     
         */
        public void setOrganizationInfo(TRequestPA.FoundationInfo.OrganizationInfo value) {
            this.organizationInfo = value;
        }

        /**
         * Gets the value of the grbsCode property.
         * 
         * @return
         *     possible object is
         *     {@link TGRBS }
         *     
         */
        public TGRBS getGRBSCode() {
            return grbsCode;
        }

        /**
         * Sets the value of the grbsCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link TGRBS }
         *     
         */
        public void setGRBSCode(TGRBS value) {
            this.grbsCode = value;
        }

        /**
         * Gets the value of the contractInfo property.
         * 
         * @return
         *     possible object is
         *     {@link TRequestPA.FoundationInfo.ContractInfo }
         *     
         */
        public TRequestPA.FoundationInfo.ContractInfo getContractInfo() {
            return contractInfo;
        }

        /**
         * Sets the value of the contractInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link TRequestPA.FoundationInfo.ContractInfo }
         *     
         */
        public void setContractInfo(TRequestPA.FoundationInfo.ContractInfo value) {
            this.contractInfo = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="number" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tContractTextCode" minOccurs="0"/>
         *         &lt;element name="IGK" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tIGK" minOccurs="0"/>
         *         &lt;element name="conclusionDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
         *         &lt;element name="regNum" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tContractRegNum" minOccurs="0"/>
         *         &lt;element name="link" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tText2000" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "number",
            "igk",
            "conclusionDate",
            "regNum",
            "link"
        })
        public static class ContractInfo {

            protected String number;
            @XmlElement(name = "IGK")
            protected String igk;
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar conclusionDate;
            protected String regNum;
            protected String link;

            /**
             * Gets the value of the number property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNumber() {
                return number;
            }

            /**
             * Sets the value of the number property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNumber(String value) {
                this.number = value;
            }

            /**
             * Gets the value of the igk property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIGK() {
                return igk;
            }

            /**
             * Sets the value of the igk property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIGK(String value) {
                this.igk = value;
            }

            /**
             * Gets the value of the conclusionDate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getConclusionDate() {
                return conclusionDate;
            }

            /**
             * Sets the value of the conclusionDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setConclusionDate(XMLGregorianCalendar value) {
                this.conclusionDate = value;
            }

            /**
             * Gets the value of the regNum property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRegNum() {
                return regNum;
            }

            /**
             * Sets the value of the regNum property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRegNum(String value) {
                this.regNum = value;
            }

            /**
             * Gets the value of the link property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLink() {
                return link;
            }

            /**
             * Sets the value of the link property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLink(String value) {
                this.link = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;choice minOccurs="0">
         *           &lt;element name="consRegistryNum" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tSvRCode"/>
         *           &lt;element name="NUBP" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tNUBP"/>
         *         &lt;/choice>
         *         &lt;element name="INN" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tINNOrganization" minOccurs="0"/>
         *         &lt;element name="fullName" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tText2000" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "consRegistryNum",
            "nubp",
            "inn",
            "fullName"
        })
        public static class OrganizationInfo {

            protected String consRegistryNum;
            @XmlElement(name = "NUBP")
            protected String nubp;
            @XmlElement(name = "INN")
            protected String inn;
            protected String fullName;

            /**
             * Gets the value of the consRegistryNum property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getConsRegistryNum() {
                return consRegistryNum;
            }

            /**
             * Sets the value of the consRegistryNum property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setConsRegistryNum(String value) {
                this.consRegistryNum = value;
            }

            /**
             * Gets the value of the nubp property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNUBP() {
                return nubp;
            }

            /**
             * Sets the value of the nubp property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNUBP(String value) {
                this.nubp = value;
            }

            /**
             * Gets the value of the inn property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getINN() {
                return inn;
            }

            /**
             * Sets the value of the inn property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setINN(String value) {
                this.inn = value;
            }

            /**
             * Gets the value of the fullName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFullName() {
                return fullName;
            }

            /**
             * Sets the value of the fullName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFullName(String value) {
                this.fullName = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence minOccurs="0">
     *         &lt;element name="TOFKInfo" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence minOccurs="0">
     *                   &lt;element name="code" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tTOFKCode" minOccurs="0"/>
     *                   &lt;element name="name" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tText2000" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="foundation" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tText2000" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tofkInfo",
        "foundation"
    })
    public static class PrintFormFieldsInfo {

        @XmlElement(name = "TOFKInfo")
        protected TRequestPA.PrintFormFieldsInfo.TOFKInfo tofkInfo;
        protected String foundation;

        /**
         * Gets the value of the tofkInfo property.
         * 
         * @return
         *     possible object is
         *     {@link TRequestPA.PrintFormFieldsInfo.TOFKInfo }
         *     
         */
        public TRequestPA.PrintFormFieldsInfo.TOFKInfo getTOFKInfo() {
            return tofkInfo;
        }

        /**
         * Sets the value of the tofkInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link TRequestPA.PrintFormFieldsInfo.TOFKInfo }
         *     
         */
        public void setTOFKInfo(TRequestPA.PrintFormFieldsInfo.TOFKInfo value) {
            this.tofkInfo = value;
        }

        /**
         * Gets the value of the foundation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFoundation() {
            return foundation;
        }

        /**
         * Sets the value of the foundation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFoundation(String value) {
            this.foundation = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence minOccurs="0">
         *         &lt;element name="code" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tTOFKCode" minOccurs="0"/>
         *         &lt;element name="name" type="{http://zakupki.gov.ru/eruz/esmv/types/base/1}tText2000" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "code",
            "name"
        })
        public static class TOFKInfo {

            protected String code;
            protected String name;

            /**
             * Gets the value of the code property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCode() {
                return code;
            }

            /**
             * Sets the value of the code property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCode(String value) {
                this.code = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="headSignatureInfo" type="{http://zakupki.gov.ru/eruz/esmv/types/1}tSignatureInfo"/>
     *         &lt;element name="accountantSignatureInfo" type="{http://zakupki.gov.ru/eruz/esmv/types/1}tSignatureInfo" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "headSignatureInfo",
        "accountantSignatureInfo"
    })
    public static class SignatoriesInfo {

        @XmlElement(required = true)
        protected TSignatureInfo headSignatureInfo;
        protected TSignatureInfo accountantSignatureInfo;

        /**
         * Gets the value of the headSignatureInfo property.
         * 
         * @return
         *     possible object is
         *     {@link TSignatureInfo }
         *     
         */
        public TSignatureInfo getHeadSignatureInfo() {
            return headSignatureInfo;
        }

        /**
         * Sets the value of the headSignatureInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link TSignatureInfo }
         *     
         */
        public void setHeadSignatureInfo(TSignatureInfo value) {
            this.headSignatureInfo = value;
        }

        /**
         * Gets the value of the accountantSignatureInfo property.
         * 
         * @return
         *     possible object is
         *     {@link TSignatureInfo }
         *     
         */
        public TSignatureInfo getAccountantSignatureInfo() {
            return accountantSignatureInfo;
        }

        /**
         * Sets the value of the accountantSignatureInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link TSignatureInfo }
         *     
         */
        public void setAccountantSignatureInfo(TSignatureInfo value) {
            this.accountantSignatureInfo = value;
        }

    }

}
